// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:3e30ab35dcdb63062dc8e2b51697101582ec6a784dcc0b54f70f5124fae96756

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./payload-check.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "payload-check", adapter });
