// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:d6217a8cd10555081d8bbbd740967034efa1259e3fe01261a8d184e72ea3fbfe

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./payload-check.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "payload-check", adapter });
