// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:3e30ab35dcdb63062dc8e2b51697101582ec6a784dcc0b54f70f5124fae96756

export type StateName = "OUTSIDE" | "IN_EFFECT" | "IN_UNKNOWN_EFFECT" | "IN_FIELD" | "IN_SETTLED_FIELD";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "Constant"; input: { kind: "boolean" | "integer" | "number" | "string"; number: number; text: string } }
  | { name: "DeclaredField"; input: { name: string } }
  | { name: "EnterEffect"; input: { name: string } }
  | { name: "GivenField"; input: { name: string } }
  | { name: "LeaveEffect"; input: {} }
  | { name: "Typed"; input: { type: "boolean" | "integer" | "number" | "string" } }
  | { name: "Unresolved"; input: {} };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   * A query that takes an `input` is a question about that input. Pass on exactly what the production code
   * asked about; a question the specification does not ask in that command makes the test fail.
   */
  queries: {
    effectDeclared(input: { name: string }): boolean;
    fieldDeclared(input: { effect: string; field: string }): boolean;
    fieldGiven(input: { effect: string; field: string }): boolean;
    fieldKind(input: { effect: string; field: string }): "boolean" | "integer" | "number" | "string" | "enum";
    hasMaximum(input: { effect: string; field: string }): boolean;
    hasMinimum(input: { effect: string; field: string }): boolean;
    maximum(input: { effect: string; field: string }): number;
    memberOf(input: { effect: string; field: string; value: string }): boolean;
    minimum(input: { effect: string; field: string }): number;
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    ReportDiagnostic(payload: { code: "missing-field" | "bad-value"; effect: string; field: string }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
