// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:b4d085aa97f446869fb63cb662797c775f939571ce692d26c11d31adef00e2b4

export type StateName = "IDLE" | "DESIGN" | "WIRING" | "GRADING" | "IMPLEMENTATION" | "DONE" | "FAILED";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "CurrentCodeGraded"; input: { passed: boolean } }
  | { name: "DesignChecked"; input: { passed: boolean } }
  | { name: "ImplementationChecked"; input: { passed: boolean } }
  | { name: "Start"; input: { attemptsPerPhase: number; rounds: number } }
  | { name: "WiringChecked"; input: { passed: boolean } };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   * A query that takes an `input` is a question about that input. Pass on exactly what the production code
   * asked about; a question the specification does not ask in that command makes the test fail.
   */
  queries: {
    boundaryChanged(): boolean;
    hasAdapter(): boolean;
    hasProductionCode(): boolean;
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    DiscardCode(payload: {}): void;
    GradeCurrentCode(payload: { round: number }): void;
    StartSession(payload: { attempt: number; phase: "design" | "wiring" | "implementation"; round: number }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
