// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:7196268ff6955912b9ccaa07d7b3f3fda876c551ab41ecd273d5a3bbfe30ac7f

export type StateName = "IDLE" | "BETWEEN_COMMANDS" | "IN_COMMAND" | "IN_CASE" | "ACCEPTED" | "REJECTED";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "AllowFrom"; input: { state: string } }
  | { name: "Begin"; input: {} }
  | { name: "EnterCase"; input: { name: string } }
  | { name: "EnterCommand"; input: { name: string } }
  | { name: "Finish"; input: {} }
  | { name: "GoTo"; input: { state: string } }
  | { name: "LeaveCommand"; input: {} }
  | { name: "UseEffect"; input: { name: string } };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   * A query that takes an `input` is a question about that input. Pass on exactly what the production code
   * asked about; a question the specification does not ask in that command makes the test fail.
   */
  queries: {
    effectDeclared(input: { name: string }): boolean;
    stateDeclared(input: { name: string }): boolean;
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    ReportDiagnostic(payload: { caseName: string; code: "unknown-state" | "unknown-effect"; command: string; subject: string }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
