// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:5631455dbf29805c91a61e777a39c30e0141743334631a9c0281429c9eb14a16

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./reference-check.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "reference-check", adapter });
