// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:7196268ff6955912b9ccaa07d7b3f3fda876c551ab41ecd273d5a3bbfe30ac7f

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./reference-check.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "reference-check", adapter });
