// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:834a9996b581b5c08427085166b5dd36fa72cf406340e55244fb8f5a555cd065

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./value-writer.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "value-writer", adapter });
