// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:834a9996b581b5c08427085166b5dd36fa72cf406340e55244fb8f5a555cd065

export type StateName = "READY";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "Constant"; input: { flag: boolean; kind: "string" | "number" | "boolean"; number: number; text: string } }
  | { name: "Reference"; input: { column: string; name: string; table: string; target: "input" | "data" | "query" | "calculation" | "decision" } }
  | { name: "WasState"; input: { state: string } };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   * A query that takes an `input` is a question about that input. Pass on exactly what the production code
   * asked about; a question the specification does not ask in that command makes the test fail.
   */
  queries: {};
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    WriteConstant(payload: { flag: boolean; kind: "string" | "number" | "boolean"; number: number; text: string }): void;
    WriteReference(payload: { text: string }): void;
    WriteWasState(payload: { state: string }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
