// Code generated by clp. DO NOT EDIT.
// ir-version: 3
// spec-hash:  sha256:a669c7860da291bd27dd3f94a1d870db03e5626a44bc1e8eb62ff0368d75ee85

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./pipeline.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "pipeline", adapter });
