// Code generated by clp. DO NOT EDIT.
// ir-version: 4
// spec-hash:  sha256:f9769d7b0cc4340b7751afc80637bc681786cfa77299fd746d86a383997f8880

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./pipeline.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "pipeline", adapter });
