// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:b4d085aa97f446869fb63cb662797c775f939571ce692d26c11d31adef00e2b4

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./pipeline.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "pipeline", adapter });
