// Code generated by clp. DO NOT EDIT.
// ir-version: 4
// spec-hash:  sha256:aab20199e00c390bb9626a43caee367fea3f4fc1571dcb953e50de2130b49f81

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./reference-check.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "reference-check", adapter });
