// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:dc3a3c0babe2ccc25ab23ed85227c74268822d8a2d033f94c9bfda54560bf609
import { interpretation, ref } from "@clp/core";
import { Pipeline } from "./pipeline.component.ts";

const Limit = { type: "integer", min: 1, max: 3 } as const;
const Count = { type: "integer", min: 1, max: 4 } as const;

const remembered = {
  maxAttempts: ref.input("attemptsPerPhase"),
  maxRounds: ref.input("rounds"),
  incremental: ref.decision("plan", "incremental"),
  round: 1,
  attempt: 1,
} as const;
const planned = {
  set: remembered,
  effects: [{ StartSession: { phase: ref.decision("plan", "phase"), round: 1, attempt: 1 } }],
} as const;

const retry = (phase: "design" | "wiring" | "implementation") =>
  ({
    set: { attempt: ref.calculation("nextAttempt") },
    effects: [{ StartSession: { phase, round: ref.data("round"), attempt: ref.calculation("nextAttempt") } }],
  }) as const;
const restart = {
  set: { round: ref.calculation("nextRound"), attempt: 1 },
  effects: [
    { DiscardCode: {}, when: "The code is being written from nothing" },
    { StartSession: { phase: "design", round: ref.calculation("nextRound"), attempt: 1 } },
  ],
} as const;

export const Interpretation = interpretation(Pipeline, {
  structure: {
    data: {
      // Whether production code existed when the run started
      incremental: "boolean",
      attempt: Count,
      round: Count,
      maxAttempts: Limit,
      maxRounds: Limit,
    },

    calculations: {
      nextAttempt: { is: "the current attempt number plus one", type: "integer" },
      nextRound: { is: "the current round number plus one", type: "integer" },
    },

    commands: {
      Start: {
        when: {
          "There is no production code yet": planned,
          "There is production code, and the boundary differs from the previous run": planned,
          "There is production code, the boundary is unchanged, and there is no adapter": planned,
          otherwise: { set: remembered, effects: [{ GradeCurrentCode: { round: 1 } }] },
        },
      },

      DesignChecked: {
        when: {
          "The check passed": {
            set: { attempt: 1 },
            effects: [{ StartSession: { phase: "wiring", round: ref.data("round"), attempt: 1 } }],
          },
          "The check was rejected and attempts remain in this phase": retry("design"),
          "The check was rejected, no attempts remain in this phase, and rounds remain": restart,
          otherwise: {},
        },
      },

      WiringChecked: {
        when: {
          "The check passed and existing code is being changed": {
            set: { attempt: 1 },
            effects: [{ GradeCurrentCode: { round: ref.data("round") } }],
          },
          "The check passed and the code is being written from nothing": {
            set: { attempt: 1 },
            effects: [{ StartSession: { phase: "implementation", round: ref.data("round"), attempt: 1 } }],
          },
          "The check was rejected and attempts remain in this phase": retry("wiring"),
          "The check was rejected, no attempts remain in this phase, and rounds remain": restart,
          otherwise: {},
        },
      },

      CurrentCodeGraded: {
        when: {
          "The check passed": {},
          otherwise: { effects: [{ StartSession: { phase: "implementation", round: ref.data("round"), attempt: 1 } }] },
        },
      },

      ImplementationChecked: {
        when: {
          "The check passed": {},
          "The check was rejected and attempts remain in this phase": retry("implementation"),
          "The check was rejected, no attempts remain in this phase, and rounds remain": restart,
          otherwise: {},
        },
      },
    },
  },

  meanings: {
    conditions: {
      "There is no production code yet": (state) => !state.hasProductionCode,
      "There is production code, and the boundary differs from the previous run": (state) =>
        state.hasProductionCode && state.boundaryChanged,
      "There is production code, the boundary is unchanged, and there is no adapter": (state) =>
        state.hasProductionCode && !state.boundaryChanged && !state.hasAdapter,

      "The check passed": (state) => state.passed === true,
      "The check passed and existing code is being changed": (state) => state.passed === true && state.incremental === true,
      "The check passed and the code is being written from nothing": (state) => state.passed === true && state.incremental === false,
      "The check was rejected and attempts remain in this phase": (state) =>
        !state.passed && (state.attempt ?? 1) < (state.maxAttempts ?? 1),
      "The check was rejected, no attempts remain in this phase, and rounds remain": (state) =>
        !state.passed && (state.attempt ?? 1) >= (state.maxAttempts ?? 1) && (state.round ?? 1) < (state.maxRounds ?? 1),

      "The code is being written from nothing": (state) => state.incremental === false,
    },

    calculations: {
      nextAttempt: (state) => (state.attempt ?? 0) + 1,
      nextRound: (state) => (state.round ?? 0) + 1,
    },

    invariants: {
      "The attempt number never exceeds the limit of attempts per phase": (state) =>
        state.status === "IDLE" || (state.attempt ?? 0) <= (state.maxAttempts ?? 0),
      "The round number never exceeds the limit of rounds": (state) =>
        state.status === "IDLE" || (state.round ?? 0) <= (state.maxRounds ?? 0),
    },
  },
});
