// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:96768450065bcf81bc2a900d8cfab48e234d90e1d3d08a6e32d4f53ae3664499
import { interpretation, ref } from "@clp/core";
import { ReferenceCheck } from "./reference-check.component.ts";

const counted = { errors: ref.calculation("nextErrors") } as const;

export const Interpretation = interpretation(ReferenceCheck, {
  structure: {
    data: {
      // Where the walk is, for the position of a diagnostic
      command: "string",
      caseName: "string",
      errors: { type: "integer", min: 0, max: 8 },
    },

    calculations: {
      nextErrors: { is: "the number of errors so far plus one", type: "integer" },
    },

    invariants: ["A walk that has started has an error count"],

    commands: {
      Begin: { set: { errors: 0 } },
      EnterCommand: { set: { command: ref.input("name"), caseName: "" } },

      AllowFrom: {
        when: {
          "The named state is not declared": {
            effects: [
              { ReportDiagnostic: { code: "unknown-state", command: ref.data("command"), caseName: "", subject: ref.input("state") } },
            ],
            set: counted,
          },
          otherwise: {},
        },
      },

      EnterCase: { set: { caseName: ref.input("name") } },

      GoTo: {
        when: {
          "The named state is not declared": {
            effects: [
              {
                ReportDiagnostic: {
                  code: "unknown-state",
                  command: ref.data("command"),
                  caseName: ref.data("caseName"),
                  subject: ref.input("state"),
                },
              },
            ],
            set: counted,
          },
          otherwise: {},
        },
      },

      UseEffect: {
        when: {
          "The named effect is not declared": {
            effects: [
              {
                ReportDiagnostic: {
                  code: "unknown-effect",
                  command: ref.data("command"),
                  caseName: ref.data("caseName"),
                  subject: ref.input("name"),
                },
              },
            ],
            set: counted,
          },
          otherwise: {},
        },
      },

      LeaveCommand: {},

      Finish: {
        from: ["BETWEEN_COMMANDS"],
        when: { "No error was counted": { goTo: "ACCEPTED" }, otherwise: { goTo: "REJECTED" } },
      },
    },
  },

  meanings: {
    conditions: {
      "The named state is not declared": (state) => !state.stateDeclared,
      "The named effect is not declared": (state) => !state.effectDeclared,
      "No error was counted": (state) => state.errors === 0,
    },

    calculations: {
      nextErrors: (state) => (state.errors ?? 0) + 1,
    },

    invariants: {
      "A walk that has started has an error count": (state) => state.status === "IDLE" || state.errors !== undefined,
    },
  },
});
