// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:151285e7a21ec2063f2ba819ef4f4b84a9fc15e74df0f726a6167edc614e0de7

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./order.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "order", adapter });
