// Code generated by clp. DO NOT EDIT.
// ir-version: 4
// spec-hash:  sha256:3e167d2a60d1d02a022d7ca4ca535aad995891350f0511959a71f08266dca651

export type StateName = "DRAFT" | "PENDING" | "PAID" | "SHIPPED" | "CANCELLED";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "Cancel"; input: {} }
  | { name: "Checkout"; input: {} }
  | { name: "PlaceOrder"; input: { customerRank: "Gold" | "Silver" | "Bronze"; listPrice: number } }
  | { name: "Ship"; input: {} };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   */
  queries: {
    isMonthEnd(): boolean;
    paymentModuleActive(): boolean;
    paymentResult(): "succeeded" | "failed";
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    IssueCoupon(payload: { type: "Premium" | "Standard" }): void;
    NotifyPaymentFailure(payload: {}): void;
    Refund(payload: {}): void;
    SendOrderConfirmation(payload: {}): void;
    SendReceipt(payload: { amount: number; discountPercent: number }): void;
    SendShippingNotice(payload: { priority: boolean }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
