// Code generated by clp. DO NOT EDIT.
// ir-version: 4
// spec-hash:  sha256:3e167d2a60d1d02a022d7ca4ca535aad995891350f0511959a71f08266dca651

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./order.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../../../specs/", import.meta.url)), component: "order", adapter });
