// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:b9d3c3a2dec12156c72a3f555e6722a180bf6860d824d51e8a735e0164dbcb91
import { component, decide, emits, interpretation, otherwise, ref, set, when } from "@clp/core";
import { PayloadCheck } from "./payload-check.component.ts";

export const Interpretation = interpretation(PayloadCheck, {
  commands: {
    EnterEffect: component(when("The entered effect is not declared", set({ effect: ref.input("name") })), otherwise(set({ effect: ref.input("name") }))),
    DeclaredField: component(
      when(
        "The effect is declared, and the specification gives no value for the declared field",
        emits("ReportDiagnostic", { code: "missing-field", effect: ref.data("effect"), field: ref.input("name") }),
      ),
      otherwise(),
    ),
    GivenField: component(
      when(
        "The effect is declared but does not declare the given field",
        emits("ReportDiagnostic", { code: "bad-value", effect: ref.data("effect"), field: ref.input("name") }),
        set({ field: ref.input("name") }),
      ),
      when("The effect is declared and declares the given field", set({ field: ref.input("name") })),
      otherwise(),
    ),
    Constant: component(
      when(
        "The field's value is still being checked, and the constant does not fit the field",
        emits("ReportDiagnostic", { code: "bad-value", effect: ref.data("effect"), field: ref.data("field") }),
      ),
      otherwise(),
    ),
    Typed: component(
      when(
        "The field's value is still being checked, and a value of that type does not fit the field",
        emits("ReportDiagnostic", { code: "bad-value", effect: ref.data("effect"), field: ref.data("field") }),
      ),
      otherwise(),
    ),
    Unresolved: component(
      when(
        "The field's value is still being checked",
        emits("ReportDiagnostic", { code: "bad-value", effect: ref.data("effect"), field: ref.data("field") }),
      ),
      otherwise(),
    ),
    LeaveEffect: component(),
  },

  meanings: {
    conditions: {
      // REVIEW: in GivenField, "the effect is declared" is read from the state (the walk is not in
      // IN_UNKNOWN_EFFECT); the command does not ask `effectDeclared` again.
      "The effect is declared and declares the given field": (state) => {
        return state.status !== "IN_UNKNOWN_EFFECT" && state.declared === true;
      },
      "The effect is declared but does not declare the given field": (state) => {
        return state.status !== "IN_UNKNOWN_EFFECT" && state.declared === false;
      },
      // REVIEW: as in GivenField, "the effect is declared" is read from the state (the walk is in IN_EFFECT).
      "The effect is declared, and the specification gives no value for the declared field": (state) => {
        return state.status === "IN_EFFECT" && state.given === false;
      },
      "The entered effect is not declared": (state) => {
        return state.declared === false;
      },
      "The field takes a boolean and the value is a boolean": (state) => {
        return state.takes === "boolean" && state.kind === "boolean";
      },
      // REVIEW: "within the field's bounds" is read as applying to both "an integer" and "a number", not only to
      // "a number".
      "The field takes a number, and the value is an integer or a number within the field's bounds": (state) => {
        if (state.takes !== "number") return false;
        if (state.kind !== "integer" && state.kind !== "number") return false;
        const value = state.number;
        if (value === undefined) return false;
        if (state.bounded === true && state.lowest !== undefined && value < state.lowest) return false;
        if (state.capped === true && state.highest !== undefined && value > state.highest) return false;
        return true;
      },
      "The field takes a string and the value is a string": (state) => {
        return state.takes === "string" && state.kind === "string";
      },
      // REVIEW: "the value is an integer" is read as `kind` being "integer". A constant of kind "number" that
      // happens to be whole (2.0) does not fit an integer field, and `number` is not checked to be whole.
      "The field takes an integer, and the value is an integer within the field's bounds": (state) => {
        if (state.takes !== "integer") return false;
        if (state.kind !== "integer") return false;
        const value = state.number;
        if (value === undefined) return false;
        if (state.bounded === true && state.lowest !== undefined && value < state.lowest) return false;
        if (state.capped === true && state.highest !== undefined && value > state.highest) return false;
        return true;
      },
      "The field takes one of a fixed set of strings, and the value is a string in that set": (state) => {
        return state.takes === "enum" && state.kind === "string" && state.inSet === true;
      },
      "The field's value is still being checked": (state) => {
        return state.status === "IN_FIELD";
      },
      "The field's value is still being checked, and a value of that type does not fit the field": (state) => {
        return state.status === "IN_FIELD" && !decide(PayloadCheck, "typeFit", state).fits;
      },
      "The field's value is still being checked, and the constant does not fit the field": (state) => {
        return state.status === "IN_FIELD" && !decide(PayloadCheck, "constantFit", state).fits;
      },
      "The value's type is integer and the field takes a number": (state) => {
        return state.type === "integer" && state.takes === "number";
      },
      // A field that takes one of a fixed set of strings ("enum") never matches: no value type is "enum".
      "The value's type is the same as what the field takes": (state) => {
        return state.type !== undefined && state.type === state.takes;
      },
    },
  },
});
