// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:d8d3dd9ff6983da085b0bc1d1c801fcfbfae435c73fae404af95fd42e5185a08
import { decide, interpretation, ref } from "@clp/core";
import { PayloadCheck } from "./payload-check.component.ts";

const badValue = { ReportDiagnostic: { code: "bad-value", effect: ref.data("effect"), field: ref.input("field") } } as const;

export const Interpretation = interpretation(PayloadCheck, {
  // Structure: what Layer 1 left as prose, as declarations. No functions.
  structure: {
    commands: {
      // The walk enters an effect and remembers its name. If the effect is not declared, an unknown-effect diagnostic is reported for it.
      EnterEffect: {
        when: {
          "The entered effect is not declared": {
            set: { effect: ref.input("name") },
            effects: [{ ReportDiagnostic: { code: "unknown-effect", effect: ref.input("name"), field: "" } }],
          },
          otherwise: { set: { effect: ref.input("name") } },
        },
      },
      // A field the specification gives to the effect being walked, with the kind of the value given. In a declared effect: if the effect does not declare the field, a bad-value diagnostic is reported for it; otherwise, if the value's kind does not fit the kind the field takes, a bad-value diagnostic is reported for it. In an effect that is not declared, nothing is checked.
      GivenField: {
        // REVIEW: `asks` belongs to the whole command, so both questions are listed for every case. The prose only
        // needs the field's kind when the effect declares the field, and needs neither answer in an effect that is
        // not declared ("nothing is checked"); the answers are ignored there, but an implementation is allowed to ask.
        asks: {
          fieldIsDeclared: { fieldDeclared: { effect: ref.data("effect"), field: ref.input("field") } },
          fieldTakes: { fieldKind: { effect: ref.data("effect"), field: ref.input("field") } },
        },
        when: {
          // REVIEW: the code for a given field the effect does not declare is "bad-value", as the command's
          // description says; the component's description lists it as a mismatch of its own, but no other code exists.
          "The effect is declared and does not declare the given field": { effects: [badValue] },
          "The effect is declared and declares the given field, and the value's kind does not fit the kind the field takes": {
            effects: [badValue],
          },
          otherwise: {},
        },
      },
      // A field the effect being walked declares. If the specification gives no value for it, a missing-field diagnostic is reported for it.
      DeclaredField: {
        asks: { fieldIsGiven: { fieldGiven: { effect: ref.data("effect"), field: ref.input("field") } } },
        when: {
          "The specification gives no value for the declared field": {
            effects: [{ ReportDiagnostic: { code: "missing-field", effect: ref.data("effect"), field: ref.input("field") } }],
          },
          otherwise: {},
        },
      },
      // REVIEW: Layer 1 does not say the effect's name is forgotten on leaving, so it stays remembered until the
      // next effect is entered.
      LeaveEffect: {},
    },
  },

  // Meaning: what each name refers to, as functions.
  meanings: {
    conditions: {
      // The value's kind is the one given to GivenField; the field's kind is the answer asked there. During other
      // commands both are unset and no row holds.
      "The value and the field are of the same kind": (state) => state.kind !== undefined && state.kind === state.fieldTakes,
      "The value is an integer and the field takes a number": (state) => state.kind === "integer" && state.fieldTakes === "number",
      "The value is one of a fixed set of strings and the field takes a string": (state) =>
        state.kind === "enum" && state.fieldTakes === "string",

      "The entered effect is not declared": (state) => state.declared === false,

      "The effect is declared and does not declare the given field": (state) =>
        state.status === "IN_EFFECT" && state.fieldIsDeclared === false,
      "The effect is declared and declares the given field, and the value's kind does not fit the kind the field takes": (state) =>
        state.status === "IN_EFFECT" && state.fieldIsDeclared === true && !decide(PayloadCheck, "compatibility", state).fits,

      "The specification gives no value for the declared field": (state) => state.fieldIsGiven === false,
    },
  },
});
