// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:ef8db6832e1f8650e7e04218bc30c770781c9e133ef2ec5c609e2562cbe5979c
import { component, description, emits, integer, interpretation, onlyWhen, otherwise, output, ref, set, when } from "@clp/core";
import { Pipeline } from "./pipeline.component.ts";

export const Interpretation = interpretation(Pipeline, {
  data: {
    incremental: "boolean",
    attempt: integer({ min: 1, max: 4 }),
    round: integer({ min: 1, max: 4 }),
    maxAttempts: integer({ min: 1, max: 3 }),
    maxRounds: integer({ min: 1, max: 3 }),
  },
  calculations: {
    nextAttempt: component(description("the current attempt number plus one"), output("integer")),
    nextRound: component(description("the current round number plus one"), output("integer")),
  },
  commands: {
    Start: component(
      when(
        "There is no production code yet",
        emits("StartSession", { phase: ref.decision("plan", "phase"), round: 1, attempt: 1 }),
        set({ maxAttempts: ref.input("attemptsPerPhase"), maxRounds: ref.input("rounds"), incremental: ref.decision("plan", "incremental"), round: 1, attempt: 1 }),
      ),
      when(
        "There is production code, and the boundary differs from the previous run",
        emits("StartSession", { phase: ref.decision("plan", "phase"), round: 1, attempt: 1 }),
        set({ maxAttempts: ref.input("attemptsPerPhase"), maxRounds: ref.input("rounds"), incremental: ref.decision("plan", "incremental"), round: 1, attempt: 1 }),
      ),
      when(
        "There is production code, the boundary is unchanged, and there is no adapter",
        emits("StartSession", { phase: ref.decision("plan", "phase"), round: 1, attempt: 1 }),
        set({ maxAttempts: ref.input("attemptsPerPhase"), maxRounds: ref.input("rounds"), incremental: ref.decision("plan", "incremental"), round: 1, attempt: 1 }),
      ),
      otherwise(
        emits("GradeCurrentCode", { round: 1 }),
        set({ maxAttempts: ref.input("attemptsPerPhase"), maxRounds: ref.input("rounds"), incremental: ref.decision("plan", "incremental"), round: 1, attempt: 1 }),
      ),
    ),
    DesignChecked: component(
      when("The check passed", emits("StartSession", { phase: "wiring", round: ref.data("round"), attempt: 1 }), set({ attempt: 1 })),
      when(
        "The check was rejected and attempts remain in this phase",
        emits("StartSession", { phase: "design", round: ref.data("round"), attempt: ref.calculation("nextAttempt") }),
        set({ attempt: ref.calculation("nextAttempt") }),
      ),
      when(
        "The check was rejected, no attempts remain in this phase, and rounds remain",
        emits("DiscardCode", onlyWhen("The code is being written from nothing")),
        emits("StartSession", { phase: "design", round: ref.calculation("nextRound"), attempt: 1 }),
        set({ round: ref.calculation("nextRound"), attempt: 1 }),
      ),
      otherwise(),
    ),
    WiringChecked: component(
      when("The check passed and existing code is being changed", emits("GradeCurrentCode", { round: ref.data("round") }), set({ attempt: 1 })),
      when(
        "The check passed and the code is being written from nothing",
        emits("StartSession", { phase: "implementation", round: ref.data("round"), attempt: 1 }),
        set({ attempt: 1 }),
      ),
      when(
        "The check was rejected and attempts remain in this phase",
        emits("StartSession", { phase: "wiring", round: ref.data("round"), attempt: ref.calculation("nextAttempt") }),
        set({ attempt: ref.calculation("nextAttempt") }),
      ),
      when(
        "The check was rejected, no attempts remain in this phase, and rounds remain",
        emits("DiscardCode", onlyWhen("The code is being written from nothing")),
        emits("StartSession", { phase: "design", round: ref.calculation("nextRound"), attempt: 1 }),
        set({ round: ref.calculation("nextRound"), attempt: 1 }),
      ),
      otherwise(),
    ),
    CurrentCodeGraded: component(when("The check passed"), otherwise(emits("StartSession", { phase: "implementation", round: ref.data("round"), attempt: 1 }))),
    ImplementationChecked: component(
      when("The check passed"),
      when(
        "The check was rejected and attempts remain in this phase",
        emits("StartSession", { phase: "implementation", round: ref.data("round"), attempt: ref.calculation("nextAttempt") }),
        set({ attempt: ref.calculation("nextAttempt") }),
      ),
      when(
        "The check was rejected, no attempts remain in this phase, and rounds remain",
        emits("DiscardCode", onlyWhen("The code is being written from nothing")),
        emits("StartSession", { phase: "design", round: ref.calculation("nextRound"), attempt: 1 }),
        set({ round: ref.calculation("nextRound"), attempt: 1 }),
      ),
      otherwise(),
    ),
  },

  meanings: {
    conditions: {
      "There is no production code yet": (state) => !state.hasProductionCode,
      "There is production code, and the boundary differs from the previous run": (state) =>
        state.hasProductionCode && state.boundaryChanged,
      "There is production code, the boundary is unchanged, and there is no adapter": (state) =>
        state.hasProductionCode && !state.boundaryChanged && !state.hasAdapter,

      "The check passed": (state) => state.passed === true,
      "The check passed and existing code is being changed": (state) => state.passed === true && state.incremental === true,
      "The check passed and the code is being written from nothing": (state) => state.passed === true && state.incremental === false,
      "The check was rejected and attempts remain in this phase": (state) =>
        !state.passed && (state.attempt ?? 1) < (state.maxAttempts ?? 1),
      "The check was rejected, no attempts remain in this phase, and rounds remain": (state) =>
        !state.passed && (state.attempt ?? 1) >= (state.maxAttempts ?? 1) && (state.round ?? 1) < (state.maxRounds ?? 1),

      "The code is being written from nothing": (state) => state.incremental === false,
    },

    calculations: {
      nextAttempt: (state) => (state.attempt ?? 0) + 1,
      nextRound: (state) => (state.round ?? 0) + 1,
    },

    invariants: {
      "The attempt number never exceeds the limit of attempts per phase": (state) =>
        state.status === "IDLE" || (state.attempt ?? 0) <= (state.maxAttempts ?? 0),
      "The round number never exceeds the limit of rounds": (state) =>
        state.status === "IDLE" || (state.round ?? 0) <= (state.maxRounds ?? 0),
    },
  },
});
