// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:432ca587397db3eda21e21d513c15cc0e776e2fde4143c401944a1d2646ae1f2
import { component, emits, from, goTo, interpretation, otherwise, ref, set, when } from "@clp/core";
import { ReferenceCheck } from "./reference-check.component.ts";

export const Interpretation = interpretation(ReferenceCheck, {
  data: {
    command: "string",
    caseName: "string",
    reported: "boolean",
  },
  invariants: [
    "A walk that has started remembers whether something was reported",
  ],
  commands: {
    Begin: component(set({ reported: false })),
    EnterCommand: component(set({ command: ref.input("name"), caseName: "" })),
    AllowFrom: component(
      when(
        "The named state is not declared",
        emits("ReportDiagnostic", { code: "unknown-state", command: ref.data("command"), caseName: "", subject: ref.input("state") }),
        set({ reported: true }),
      ),
      otherwise(),
    ),
    EnterCase: component(set({ caseName: ref.input("name") })),
    GoTo: component(
      when(
        "The named state is not declared",
        emits("ReportDiagnostic", { code: "unknown-state", command: ref.data("command"), caseName: ref.data("caseName"), subject: ref.input("state") }),
        set({ reported: true }),
      ),
      otherwise(),
    ),
    UseEffect: component(
      when(
        "The named effect is not declared",
        emits("ReportDiagnostic", { code: "unknown-effect", command: ref.data("command"), caseName: ref.data("caseName"), subject: ref.input("name") }),
        set({ reported: true }),
      ),
      otherwise(),
    ),
    LeaveCommand: component(),
    Finish: component(from("BETWEEN_COMMANDS"), when("Nothing was reported", goTo("ACCEPTED")), otherwise(goTo("REJECTED"))),
  },

  meanings: {
    conditions: {
      "The named state is not declared": (state) => state.declared === false,
      "The named effect is not declared": (state) => state.declared === false,
      "Nothing was reported": (state) => state.reported === false,
    },

    invariants: {
      "A walk that has started remembers whether something was reported": (state) => state.status === "IDLE" || state.reported !== undefined,
    },
  },
});
