// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:4c3fa6a76e702bf68a6d1a7b0ddcf127ef0d1c8695b2da9dd8ccd2110a1403c8
import { calculate, decide, interpretation, ref } from "@clp/core";
import { ValueWriter } from "./value-writer.component.ts";

export const Interpretation = interpretation(ValueWriter, {
  // Structure: what Layer 1 left as prose, as declarations. No functions.
  structure: {
    commands: {
      // A constant written in the specification. `kind` says what it is; `text` holds a string, `number` a number, `flag` a boolean. It is written as a constant with exactly the kind, text, number and flag it was given.
      Constant: {
        effects: [{ WriteConstant: { kind: ref.input("kind"), text: ref.input("text"), number: ref.input("number"), flag: ref.input("flag") } }],
      },
      // A reference to something the specification declares. `target` says what kind of thing. `name` is the thing's name; for a column of a decision table, `table` and `column` name it instead. It is written as a reference whose text is the reference text.
      Reference: {
        effects: [{ WriteReference: { text: ref.calculation("referenceText") } }],
      },
      // One of the states listed by a reference to the state before the command. It is written as that state.
      WasState: {
        effects: [{ WriteWasState: { state: ref.input("state") } }],
      },
    },
  },

  // Meaning: what each name refers to, as functions.
  meanings: {
    conditions: {
      "The reference is to a calculation": (state) => {
        return state.target === "calculation";
      },
      "The reference is to a query answer": (state) => {
        return state.target === "query";
      },
      "The reference is to an input of the command": (state) => {
        return state.target === "input";
      },
      "The reference is to remembered data": (state) => {
        return state.target === "data";
      },
    },
    calculations: {
      // The prefix the reference form gives, followed by what is referred to: the name, or, for a column of a decision table, the table, a dot, and the column. Nothing else is added and nothing is trimmed.
      // REVIEW: "for a column of a decision table" is read as `target` being "decision"; `name` is then ignored,
      // and `table` and `column` are ignored for every other target, whatever they hold.
      referenceText: (state) => {
        const prefix = decide(ValueWriter, "form", state).prefix;
        if (state.target === "decision") return prefix + (state.table ?? "") + "." + (state.column ?? "");
        return prefix + (state.name ?? "");
      },
    },
  },
});
