// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:ce958488f2f05edc246fcf9d139365c7ca64f73d8258cb4044233572ae5e2728
import { component, decide, emits, from, goTo, interpretation, onlyWhen, otherwise, ref, set, when } from "@clp/core";
import { Order } from "./order.component.ts";

export const Interpretation = interpretation(Order, {
  commands: {
    PlaceOrder: component(emits("SendOrderConfirmation"), set({ rank: ref.input("customerRank"), price: ref.input("listPrice") })),
    Checkout: component(
      when(
        "The payment succeeded",
        emits("SendReceipt", { discountPercent: ref.decision("campaign", "discountPercent"), amount: ref.calculation("amountCharged") }),
        emits("IssueCoupon", { type: ref.decision("campaign", "coupon") }, onlyWhen(ref.decision("campaign", "grantsCoupon"))),
      ),
      otherwise(emits("NotifyPaymentFailure")),
    ),
    Ship: component(goTo("SHIPPED"), emits("SendShippingNotice", { priority: ref.decision("shipping", "priority") })),
    Cancel: component(from("PENDING", "PAID"), goTo("CANCELLED"), emits("Refund", onlyWhen(ref.was("PAID")))),
  },

  meanings: {
    conditions: {
      "The customer is a Gold member and it is month-end": (state) => state.rank === "Gold" && state.isMonthEnd,
      "The customer is a Silver member": (state) => state.rank === "Silver",
      "The customer is a Gold member, or the order is 10,000 yen or more": (state) =>
        state.rank === "Gold" || (state.price ?? 0) >= 10_000,
      "The external payment module is active": (state) => state.paymentModuleActive,
      "The payment succeeded": (state) => state.paymentResult === "succeeded",
    },

    calculations: {
      amountCharged: (state) =>
        Math.floor(((state.price ?? 0) * (100 - decide(Order, "campaign", state).discountPercent)) / 100),
    },

    // These check the spec itself, not the implementation.
    invariants: {
      "Every order past the draft state has a member rank and a price": (state) =>
        state.status === "DRAFT" || (state.rank !== undefined && state.price !== undefined),
    },
  },
});
