import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { after, test } from "node:test";
import { extract } from "../src/extract.ts";
import { accept, interpret } from "../src/interpret.ts";
import { loadSpecs, stampIn } from "../src/loader.ts";
import type { Assignment, ImplementationStrategy } from "../src/strategy.ts";
import { unstamped } from "./support.ts";

// 解釈 (Layer 2) を導く工程。LLM の代役として、決まった内容を書く Strategy を使う。
// 仕様のコピーは packages/cli 配下に置く（@clp/core を解決できる場所）

const repoRoot = join(import.meta.dirname, "../../..");
const tmpRoot = join(import.meta.dirname, ".tmp-interpret");
mkdirSync(tmpRoot, { recursive: true });
after(() => rmSync(tmpRoot, { recursive: true, force: true }));

// 例の解釈の中身（先頭の、生成物であることとハッシュの行を除いたもの）
const reviewed = unstamped(readFileSync(join(repoRoot, "examples/checkout-ts/specs/order.interpretation.ts"), "utf8")).replace(/^\/\/ Code generated[^\n]*\n/, "");

// 例の決定表とコンポーネント (Layer 1) だけを写した仕様ディレクトリ（解釈は無い）
function specDir() {
  const dir = mkdtempSync(join(mkdtempSync(join(tmpRoot, "d-")), "specs-"));
  for (const name of ["order.decisions.ts", "order.component.ts"]) copyFileSync(join(repoRoot, "examples/checkout-ts/specs", name), join(dir, name));
  return dir;
}
// 仕様を写して、Layer 1 を書き換えたもの。別のディレクトリにする
// （同じプロセスで同じファイルを読み直しても、モジュールのキャッシュのために前の内容が返るため）
function fork(from: string, edit: (component: string) => string) {
  const dir = mkdtempSync(join(mkdtempSync(join(tmpRoot, "d-")), "specs-"));
  for (const name of readdirSync(from)) {
    const text = readFileSync(join(from, name), "utf8");
    writeFileSync(join(dir, name), name === "order.component.ts" ? edit(text) : text);
  }
  return dir;
}
const replaced = (from: string, to: string) => (text: string) => {
  assert.ok(text.includes(from), from);
  return text.replace(from, to);
};
const DRAFT = "order.interpretation.draft.ts";
const FINAL = "order.interpretation.ts";

// 呼ばれるたびに決まった下書きを書き、作業場所で見えたものを記録する
function scripted(drafts: string[], options: { file?: string; extra?: (assignment: Assignment) => void } = {}) {
  const seen: { request: string; start: string; files: string[]; attempt: number }[] = [];
  const strategy: ImplementationStrategy = {
    name: "scripted",
    run(assignment) {
      const file = join(assignment.dir, "spec", options.file ?? DRAFT);
      seen.push({
        request: readFileSync(join(assignment.dir, "clp/REQUEST.md"), "utf8"),
        start: readFileSync(file, "utf8"),
        files: (readdirSync(join(assignment.dir, "spec")) as string[]).sort(),
        attempt: assignment.attempt,
      });
      writeFileSync(file, drafts[Math.min(seen.length, drafts.length) - 1]);
      options.extra?.(assignment);
    },
  };
  return { strategy, seen };
}

const compile = (dir: string, ...flags: string[]) =>
  spawnSync(process.execPath, [join(repoRoot, "packages/cli/bin/clp.ts"), "compile", dir, ...flags], { encoding: "utf8" });

test("解釈: Layer 1 が名前を挙げたものを並べた雛形から始め、検査に通ったら下書きとして書き出す", async () => {
  const dir = specDir();
  const { strategy, seen } = scripted([reviewed]);
  const result = await interpret({ specs: dir, strategy });

  assert.ok(result.status === "interpreted" && result.attempts === 1 && result.component === "order");
  // エージェントには Layer 1 のファイルと、書くべきファイルが渡る
  assert.deepEqual(seen[0].files, ["order.component.ts", "order.decisions.ts", DRAFT]);
  // 雛形: コマンドは、文をコメントに添えた空の宣言。Layer 1 が場合分けを書いたコマンドは、場合ごと
  assert.match(seen[0].start, /\/\/ A pending or paid order can be cancelled\. If the order had been paid, a refund is issued\.\n      Cancel: \{\},/);
  assert.match(seen[0].start, /Checkout: \{\n        when: \{\n          \/\/ A receipt is sent[^\n]*\n          "The payment succeeded": \{\},\n          \/\/ The customer is notified[^\n]*\n          "otherwise": \{\},/);
  // Layer 1 が構造で書いた語彙 (states など) は、雛形に出ない
  assert.doesNotMatch(seen[0].start, /\/\/ TODO:/);
  assert.match(seen[0].start, /"The customer is a Silver member": \(state\) => \{\n        throw new Error\("TODO"\);/);
  assert.match(seen[0].start, /\/\/ price × \(100 − discount percent\) ÷ 100, rounded down to a whole yen\n      amountCharged: \(state\) =>/);
  assert.match(seen[0].request, /^# Write the interpretation of a specification \(attempt 1\)/);
  assert.match(seen[0].request, /You cannot override what Layer 1 wrote as structure/);

  // 書き出された下書きには、生成物であることと、導いたときの Layer 1 のハッシュが記される
  const draft = readFileSync(join(dir, DRAFT), "utf8");
  assert.match(draft, /^\/\/ Code generated by clp interpret\. Do not edit[^\n]*\n\/\/ layer1: sha256:[0-9a-f]{64}\n/);
  assert.ok(draft.endsWith(reviewed));
});

test("解釈: 人が確定するまで、検証には使われない。確定すると、下書きが確定版になる", async () => {
  const dir = specDir();
  await interpret({ specs: dir, strategy: scripted([reviewed]).strategy });

  // 既定の読み込みは下書きを無視するので、解釈は無いまま
  assert.deepEqual(extract(await loadSpecs(dir)).diagnostics.map((d) => d.code), ["unbound-specification"]);
  // 下書きを読むよう明示したときだけ、仕様として通る
  assert.equal(compile(dir, "--drafts").status, 0);

  assert.deepEqual(await accept({ specs: dir }), { accepted: [join(dir, FINAL)], problems: [] });
  assert.ok(!existsSync(join(dir, DRAFT)));
  assert.equal(compile(dir).status, 0);
  // もう導くものは無い
  const again = scripted([reviewed]);
  assert.deepEqual(await interpret({ specs: dir, strategy: again.strategy }), { status: "up-to-date" });
  assert.deepEqual(again.seen, []);
  assert.deepEqual(await accept({ specs: dir }), { accepted: [], problems: [] });
});

test("解釈: 検査に落ちたら、書き直させる (型エラー、条件の衝突、Layer 1 の書き換え)", async () => {
  const typo = reviewed.replace("state.paymentModuleActive", "state.paymentModuleActiv");
  // シルバー会員の条件を「常に真」にすると、ゴールド会員かつ月末の条件と同時に成り立つ
  const conflicting = reviewed.replace('(state) => state.rank === "Silver"', "() => true");
  // Layer 1 が決めた遷移先 (PAID) を、解釈が書き換えている
  const overriding = reviewed.replace('"The payment succeeded": {', '"The payment succeeded": {\n            goTo: "SHIPPED",');
  assert.ok(typo !== reviewed && conflicting !== reviewed && overriding !== reviewed);
  const dir = specDir();
  const { strategy, seen } = scripted([typo, conflicting, overriding, reviewed]);
  const result = await interpret({ specs: dir, strategy, maxAttempts: 4 });

  assert.ok(result.status === "interpreted" && result.attempts === 4);
  assert.match(seen[1].request, /Problems found in the previous attempt[\s\S]*type-error[\s\S]*paymentModuleActiv/);
  assert.match(seen[2].request, /Problems found in the previous attempt[\s\S]*複数の条件が同時に成立しました/);
  assert.match(seen[3].request, /Problems found in the previous attempt[\s\S]*bad-interpretation[\s\S]*コマンド "Checkout" の条件 "The payment succeeded" の goTo は Layer 1 に書かれているので、解釈では書けません/);
  // 2回目からは、前回の下書きから始まる（先頭の行は除いて渡す）
  assert.equal(seen[1].start, typo);
});

test("解釈: 上限回数まで直らなければ失敗で終わり、問題を報告する。仕様のファイルを書き換えたら差し戻す", async () => {
  const unfinished = reviewed.replace('(state) => state.paymentResult === "succeeded"', '() => { throw new Error("TODO"); }');
  const failed = await interpret({ specs: specDir(), strategy: scripted([unfinished]).strategy, maxAttempts: 2 });
  assert.ok(failed.status === "failed" && failed.attempts === 2);
  assert.match(failed.problems ?? "", /TODO/);

  const dir = specDir();
  const original = readFileSync(join(dir, "order.component.ts"), "utf8");
  const { strategy, seen } = scripted([reviewed], {
    extra: ({ dir: sandbox, attempt }) => {
      if (attempt === 1) writeFileSync(join(sandbox, "spec/order.component.ts"), "// changed\n");
    },
  });
  const result = await interpret({ specs: dir, strategy });
  assert.ok(result.status === "interpreted" && result.attempts === 2);
  assert.match(seen[1].request, /Only order\.interpretation\.draft\.ts may be edited, but these files were changed: order\.component\.ts/);
  assert.equal(readFileSync(join(dir, "order.component.ts"), "utf8"), original);
});

test("解釈: 疑問点 (// REVIEW:) を集めて返す。添付資料を渡せる", async () => {
  const doubtful = reviewed.replace("      // ref.was(...): the state before the command", "      // REVIEW: does a pending order that failed to pay count as paid?");
  assert.notEqual(doubtful, reviewed);
  const { strategy, seen } = scripted([doubtful]);
  const result = await interpret({
    specs: specDir(),
    strategy,
    assets: [
      { kind: "file", name: "glossary.md", content: "- month-end: the last day." },
      { kind: "text", text: "Prices never include tax." },
    ],
  });
  assert.ok(result.status === "interpreted");
  assert.deepEqual(result.questions.map((q) => q.text), ["does a pending order that failed to pay count as paid?"]);
  assert.ok(readFileSync(result.draft, "utf8").split("\n")[result.questions[0].line - 1].includes("REVIEW:"));
  assert.match(seen[0].request, /## Project conventions[\s\S]*- Prices never include tax\.[\s\S]*`clp\/assets\/glossary\.md`/);
});

test("解釈: Layer 1 の文が変わったら、いまの解釈を出発点にして直させる。確定版は書き換えない", async () => {
  const accepted = specDir();
  await interpret({ specs: accepted, strategy: scripted([reviewed]).strategy });
  await accept({ specs: accepted });
  const final = readFileSync(join(accepted, FINAL), "utf8");

  // 払い戻しの文を変える（支払い済みに加えて、保留中でも払い戻す）
  const dir = fork(accepted, replaced("If the order had been paid, a refund is issued.", "A refund is always issued."));
  // 古い解釈は、正解として使われない
  assert.match(compile(dir).stderr, /stale-interpretation/);

  const updated = reviewed.replace('effects: [{ Refund: {}, when: ref.was("PAID") }]', "effects: [{ Refund: {} }]");
  assert.notEqual(updated, reviewed);
  const { strategy, seen } = scripted([updated]);
  const result = await interpret({ specs: dir, strategy });

  assert.ok(result.status === "interpreted");
  assert.equal(result.updates, join(dir, FINAL));
  assert.match(seen[0].request, /^# Update the interpretation of a specification/);
  assert.match(seen[0].request, /Change only what Layer 1 now requires/);
  assert.match(seen[0].request, /Problems with the current interpretation[\s\S]*stale-interpretation/);
  // 構造が変わったのは Cancel だけ（文が変わったので説明も変わる）。語彙とほかのコマンドは、そのまま
  assert.deepEqual(result.changed, ["Cancel"]);
  assert.equal(result.unchanged, 11);
  // 出発点は、いまの解釈。作業場所に、確定版は置かれない
  assert.equal(seen[0].start, reviewed);
  assert.deepEqual(seen[0].files, ["order.component.ts", "order.decisions.ts", DRAFT]);
  // 確定版はそのまま。確定すると置き換わり、いまの Layer 1 のハッシュが記される
  assert.equal(readFileSync(join(dir, FINAL), "utf8"), final);
  await accept({ specs: dir });
  assert.ok(readFileSync(join(dir, FINAL), "utf8").endsWith(updated));
  assert.notEqual(stampIn(readFileSync(join(dir, FINAL), "utf8")), stampIn(final));
  assert.equal(compile(dir).status, 0);
});

test("確定: 文を直したが解釈はそのままでよいとき、導き直さずに確定できる。合わなくなっていれば断る", async () => {
  const accepted = specDir();
  await interpret({ specs: accepted, strategy: scripted([reviewed]).strategy });
  await accept({ specs: accepted });

  // 言い回しだけを変える
  const dir = fork(accepted, replaced("An order confirmation is sent.", "A confirmation of the order is sent."));
  assert.match(compile(dir).stderr, /stale-interpretation/);
  assert.deepEqual(await accept({ specs: dir }), { accepted: [join(dir, FINAL)], problems: [] });
  assert.equal(compile(dir).status, 0);

  // 解釈が使っている副作用を、Layer 1 から消す
  const broken = fork(accepted, replaced('    Refund: description("What the customer paid is returned."),\n', ""));
  const refused = await accept({ specs: broken });
  assert.deepEqual(refused.accepted, []);
  assert.match(refused.problems[0], /order: 解釈が、いまの Layer 1 に合いません/);
});

test("2つの解釈: 同じ語彙のもとで独立に導かせ、同じコマンド列で実行して、食い違う所を報告する", async () => {
  // 2つ目は、払い戻しを「支払い済みのときだけ」ではなく「常に」と読んだ
  const always = reviewed.replace('effects: [{ Refund: {}, when: ref.was("PAID") }]', "effects: [{ Refund: {} }]");
  const dir = specDir();
  const { strategy, seen } = scripted([reviewed, always]);
  const result = await interpret({ specs: dir, strategy, sessions: 2 });

  assert.ok(result.status === "interpreted" && result.comparisons?.[0].status === "compared");
  // 2つ目のセッションは、1つ目の下書きを見ない。Layer 1 が書かなかった入力が、埋めてある
  assert.equal(seen.length, 2);
  assert.match(seen[1].request, /The vocabulary is fixed/);
  assert.match(seen[1].start, /Cancel: \{ input: \{\}, \},/);
  assert.doesNotMatch(seen[1].start, /Refund/);
  // 食い違いは Cancel にだけある。最短のコマンド列（保留中の注文のキャンセル）で示される
  assert.deepEqual(result.comparisons?.[0].differences.map((d) => d.command), ["Cancel"]);
  const [difference] = result.comparisons![0].differences;
  assert.deepEqual(difference.steps.map((step) => `${step.from}:${step.command}`), ["DRAFT:PlaceOrder", "PENDING:Cancel"]);
  assert.deepEqual(difference.first, { state: "CANCELLED", effects: [] });
  assert.deepEqual(difference.other, { state: "CANCELLED", effects: [{ name: "Refund", payload: {} }] });
  // 残るのは1つ目の下書きだけ。2つ目のための写しは消える
  assert.ok(readFileSync(join(dir, DRAFT), "utf8").endsWith(reviewed));
  assert.deepEqual(readdirSync(dirname(dir)).filter((name) => name.startsWith(".tmp-clp-interpret-")), []);
});

test("2つの解釈: 一致すれば、食い違いは無い。2つ目が語彙を変えたら差し戻す", async () => {
  const same = await interpret({ specs: specDir(), strategy: scripted([reviewed, reviewed]).strategy, sessions: 2 });
  assert.ok(same.status === "interpreted" && same.comparisons?.[0].status === "compared");
  assert.deepEqual(same.comparisons?.[0].differences, []);

  // 2つ目が、キャンセルに入力を足した（境界が変わる）
  const widened = reviewed.replace('Cancel: { from: ["PENDING", "PAID"],', 'Cancel: { input: { reason: "string" }, from: ["PENDING", "PAID"],');
  assert.notEqual(widened, reviewed);
  const { strategy, seen } = scripted([reviewed, widened, reviewed]);
  const result = await interpret({ specs: specDir(), strategy, sessions: 2 });
  assert.ok(result.status === "interpreted" && result.comparisons?.[0].status === "compared");
  assert.match(seen[2].request, /Problems found in the previous attempt[\s\S]*The fixed vocabulary was changed/);
});

test("3つ以上の解釈: 1つ目と、ほかのそれぞれを比べる。どれも互いの下書きを見ない", async () => {
  const always = reviewed.replace('effects: [{ Refund: {}, when: ref.was("PAID") }]', "effects: [{ Refund: {} }]");
  // 3つ目は、失敗した支払いのあとも通知しないと読んだ
  const silent = reviewed.replace("otherwise: { effects: [{ NotifyPaymentFailure: {} }] },", "otherwise: {},");
  assert.notEqual(silent, reviewed);
  const dir = specDir();
  const { strategy, seen } = scripted([reviewed, always, silent, reviewed]);
  const result = await interpret({ specs: dir, strategy, sessions: 4 });

  assert.ok(result.status === "interpreted");
  assert.deepEqual(result.comparisons?.map((c) => [c.session, c.status, c.differences.map((d) => d.command)]), [
    [2, "compared", ["Cancel"]],
    [3, "compared", ["Checkout"]],
    [4, "compared", []],
  ]);
  assert.equal(seen.length, 4);
  for (const later of seen.slice(1)) assert.doesNotMatch(later.start, /Refund|NotifyPaymentFailure: \{\} \}\]/);
  assert.ok(readFileSync(join(dir, DRAFT), "utf8").endsWith(reviewed));
});

test("比較: 意味の関数に書かれた定数を、入力の生成に混ぜる（自由な文字列を定数と比べる条件の違いを見つける）", async () => {
  const dir = mkdtempSync(join(mkdtempSync(join(tmpRoot, "d-")), "specs-"));
  writeFileSync(
    join(dir, "gate.component.ts"),
    `import { component, description } from "@clp/core";\nexport const Gate = component(description("A gate that opens for gold members."));\n`,
  );
  const gate = (rank: string) => `import { interpretation } from "@clp/core";
import { Gate } from "./gate.component.ts";
export const Interpretation = interpretation(Gate, {
  structure: {
    states: ["CLOSED", "OPEN"],
    init: "CLOSED",
    commands: { Arrive: { input: { rank: "string" }, from: ["CLOSED"], when: { "The member is gold": { goTo: "OPEN" }, otherwise: {} } } },
  },
  meanings: { conditions: { "The member is gold": (state) => state.rank === "${rank}" } },
});
`;
  const result = await interpret({ specs: dir, strategy: scripted([gate("GOLD"), gate("gold")], { file: "gate.interpretation.draft.ts" }).strategy, sessions: 2 });
  assert.ok(result.status === "interpreted");
  const [difference] = result.comparisons![0].differences;
  assert.equal(difference.command, "Arrive");
  assert.ok(["GOLD", "gold"].includes(difference.steps[0].input.rank as string));
});

test("比較: 1つのコマンドに食い違いが複数あれば、観点ごとに報告する。ほかのコマンドの食い違いに隠れない", async () => {
  // もう一方は、支払いの成功で: 領収書の割引率を常に 0 にし、クーポンを出さない。出荷では優先扱いを常に付ける
  const other = reviewed
    .replace('discountPercent: ref.decision("campaign", "discountPercent"),', "discountPercent: 0,")
    .replace('{ IssueCoupon: { type: ref.decision("campaign", "coupon") }, when: ref.decision("campaign", "grantsCoupon") },', "")
    .replace('{ SendShippingNotice: { priority: ref.decision("shipping", "priority") } }', "{ SendShippingNotice: { priority: true } }")
    .replace('Cancel: { from: ["PENDING", "PAID"], goTo: "CANCELLED", effects: [{ Refund: {}, when: ref.was("PAID") }] }', 'Cancel: { from: ["PENDING"], goTo: "CANCELLED" }');
  const log: string[] = [];
  const result = await interpret({ specs: specDir(), strategy: scripted([reviewed, other]).strategy, sessions: 2, log: (line) => log.push(line) });
  assert.ok(result.status === "interpreted");
  assert.equal(result.comparisons![0].status, "compared", log.join("\n"));
  assert.deepEqual(result.comparisons![0].differences.map((d) => `${d.command}:${d.aspect}`), [
    // 支払い済みの注文をキャンセルできるかどうか
    "Cancel:runs",
    // 領収書とクーポンは、別々に報告される
    "Checkout:effect:IssueCoupon",
    "Checkout:effect:SendReceipt",
    // 支払いの食い違いの先にある、出荷の食い違いも見つかる
    "Ship:effect:SendShippingNotice",
  ]);
  const coupon = result.comparisons![0].differences[1];
  assert.deepEqual(coupon.steps.map((step) => step.command), ["PlaceOrder", "Checkout"]);
});

// 文だけのコンポーネント。構造は、すべて解釈が決める
const COUNTER = `import { component, description } from "@clp/core";
export const Counter = component(description("A counter that can be raised by a step. It reports each new total. It can be closed."));
`;
const counter = (close: string) => `import { interpretation, ref } from "@clp/core";
import { Counter } from "./counter.component.ts";

export const Interpretation = interpretation(Counter, {
  structure: {
    states: ["OPEN", "CLOSED"],
    init: "OPEN",
    data: { total: { type: "integer" } },
    effects: { ReportTotal: { input: { total: "integer" } } },
    calculations: { raised: { is: "the total so far (0 if none) plus the step", output: "integer" } },
    commands: {
      Raise: {
        input: { step: { type: "integer", min: 0, max: 10 } },
        from: ["OPEN"],
        set: { total: ref.calculation("raised") },
        effects: [{ ReportTotal: { total: ref.calculation("raised") } }],
      },
      Close: ${close},
    },
  },
  meanings: { conditions: {}, calculations: { raised: (state) => (state.total ?? 0) + (state.step ?? 0) } },
});
`;

test("文だけのコンポーネント: 雛形は、決めるべきものを TODO で示す。2つ目には、1つ目が決めた語彙が渡る", async () => {
  const dir = mkdtempSync(join(mkdtempSync(join(tmpRoot, "d-")), "specs-"));
  writeFileSync(join(dir, "counter.component.ts"), COUNTER);
  const file = "counter.interpretation.draft.ts";
  // 2つ目は、閉じたあとも数えられると読んだ（Close で状態を変えない）
  const { strategy, seen } = scripted([counter(`{ from: ["OPEN"], goTo: "CLOSED" }`), counter(`{ from: ["OPEN"] }`)], { file });
  const result = await interpret({ specs: dir, strategy, sessions: 2 });

  assert.ok(result.status === "interpreted" && result.comparisons?.[0].status === "compared");
  for (const key of ["states", "init", "data", "queries", "effects", "commands"]) assert.match(seen[0].start, new RegExp(`// TODO: ${key} —`));
  // 2つ目の雛形: 状態・初期状態・副作用・コマンドの入力が埋めてあり、data は自分で決める
  assert.match(seen[1].start, /states: \[\n      "OPEN",\n      "CLOSED"\n    \],/);
  assert.match(seen[1].start, /init: "OPEN",/);
  assert.match(seen[1].start, /Raise: \{ input: \{\n        "step": \{/);
  assert.match(seen[1].start, /\/\/ TODO: data —/);
  assert.deepEqual(result.comparisons?.[0].differences.map((d) => d.command), ["Close"]);
  assert.deepEqual(result.comparisons![0].differences[0].first, { state: "CLOSED", effects: [] });
  assert.deepEqual(result.comparisons![0].differences[0].other, { state: "OPEN", effects: [] });
});

test("解釈: コンポーネントが複数あれば、解釈が要る最初のものを選ぶ。名前で選ぶこともできる", async () => {
  const dir = specDir();
  writeFileSync(join(dir, "counter.component.ts"), COUNTER);
  const full = counter(`{ from: ["OPEN"], goTo: "CLOSED" }`);
  const first = await interpret({ specs: dir, strategy: scripted([full], { file: "counter.interpretation.draft.ts" }).strategy });
  assert.ok(first.status === "interpreted" && first.component === "counter");
  // 下書きが、いまの Layer 1 のものであれば、次へ進む
  const second = await interpret({ specs: dir, strategy: scripted([reviewed]).strategy });
  assert.ok(second.status === "interpreted" && second.component === "order");
  assert.deepEqual((await accept({ specs: dir })).accepted.map((path) => path.slice(dir.length + 1)), ["counter.interpretation.ts", FINAL]);
  assert.equal(compile(dir).status, 0);
  const chosen = await interpret({ specs: dir, component: "order", strategy: scripted([reviewed]).strategy });
  assert.deepEqual(chosen, { status: "up-to-date" });
});
