import { createHash } from "node:crypto";
import { relative, sep } from "node:path";
import type { DomainModel, FieldSchema } from "@aac/core";
import { stableStringify } from "./extract.ts";

// テスト側ファイルの生成。フレームワークが生成するのはテスト側だけで、本番コードには何も置かない。
// 出力は IR だけから決まる（日時・CLI バージョンは埋めない）。

export type Ir = {
  irVersion: number;
  behaviors: { name: string; preconditions: string[]; transitions: Record<string, unknown> }[];
  decisions: Record<string, { bound: boolean; rows: Record<string, unknown> }>;
  model?: DomainModel;
};

export const TEST_DIR = "aac";
export const SOURCE_DIR = "src";

export const FILES = {
  ir: "ir.json",
  contract: "adapter.contract.ts",
  adapter: "adapter.ts",
  verify: "verify.ts",
  request: "REQUEST.md",
} as const;

export function specHash(ir: Ir): string {
  return `sha256:${createHash("sha256").update(stableStringify(ir)).digest("hex")}`;
}

function header(ir: Ir): string {
  return `// Code generated by aac. DO NOT EDIT.\n// ir-version: ${ir.irVersion}\n// spec-hash:  ${specHash(ir)}\n`;
}

const union = (values: readonly string[]) => values.map((value) => JSON.stringify(value)).join(" | ") || "never";

function fieldType(schema: FieldSchema): string {
  return typeof schema === "string" ? schema : union(schema);
}

function shape(fields: Record<string, FieldSchema>): string {
  const entries = Object.keys(fields).sort().map((key) => `${key}: ${fieldType(fields[key])}`);
  return `{ ${entries.join("; ")} }`;
}

export function generateContract(ir: Ir): string {
  const model = requireModel(ir);
  const commands = Object.keys(model.commands)
    .sort()
    .map((action) => `  | { action: ${JSON.stringify(action)}; payload: ${shape(model.commands[action])} }`);
  const outcomes = [...new Set(ir.behaviors.flatMap((behavior) => Object.keys(behavior.transitions)))].sort();

  return `${header(ir)}
export type StateName = ${union(model.states)};
export type StateData = ${shape(model.data)};
export type Command =
${commands.join("\n")};
export type ActionName = ${union(ir.behaviors.map((behavior) => behavior.name))};
export type Outcome = ${union(outcomes)};

// PBT はこのインターフェースだけを通して本番システムを操作する
export interface TargetSystemAdapter {
  /** 【分離契約】1回の試行の開始前に呼ばれる。本番システムをまっさらな状態にする。 */
  setupIsolation(): Promise<void>;
  /** 【分離契約】試行の終了後（成功・失敗問わず）に呼ばれる。副作用を完全に破棄する。 */
  teardownIsolation(): Promise<void>;
  /** 検証の出発点となる状態を本番システムに用意する。data は加工せずそのまま本番コードへ渡す。 */
  givenState(state: StateName, data: StateData): Promise<void>;
  /** アクションを実行する。outcome は IR の transitions のキー（アクションの結果の種類）。 */
  executeAction(action: ActionName, outcome: Outcome): Promise<void>;
  /** 現在の状態名を返す。 */
  getCurrentState(): Promise<StateName>;
  /** setupIsolation 以降に発行された Command を発行順に返す。 */
  getFiredCommands(): Promise<Command[]>;
}
`;
}

export function generateAdapterSkeleton(): string {
  const methods = [
    "setupIsolation()",
    "teardownIsolation()",
    "givenState(state, data)",
    "executeAction(action, outcome)",
    "getCurrentState()",
    "getFiredCommands()",
  ];
  return `import type { TargetSystemAdapter } from "./${FILES.contract}";

// ../${SOURCE_DIR}/ の本番コードを import し、各メソッドから呼び出す。業務ロジックはここに書かない。
export const adapter: TargetSystemAdapter = {
${methods.map((method) => `  async ${method} {\n    throw new Error("not implemented");\n  },`).join("\n")}
};
`;
}

export function generateVerify(ir: Ir, testDir: string, specsDir: string): string {
  const specs = relative(testDir, specsDir).split(sep).join("/");
  return `${header(ir)}
import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./${FILES.adapter}";

await runPbt({ specs: fileURLToPath(new URL(${JSON.stringify(specs + "/")}, import.meta.url)), adapter });
`;
}

export function requireModel(ir: Ir): DomainModel {
  if (!ir.model) throw new Error("仕様に DomainModel がありません（状態・データ・Command の定義が必要です）");
  return ir.model;
}
