import { createHash } from "node:crypto";
import { posix, relative, sep } from "node:path";
import type { FieldSchema } from "@clp/core";
import { stableStringify } from "./extract.ts";
import type { SpecModel } from "./extract.ts";
import { CONTROL_DIR, DEFAULT_SOURCE_DIR, dirFrom, importPath, testsDirOf } from "./layout.ts";
import type { Workspace } from "./layout.ts";

// テスト側ファイルの生成 (TypeScript を対象とするとき)。フレームワークが生成するのはテスト側だけで、本番コードには何も置かない。
// 出力は IR だけから決まる（日時・CLI バージョンは埋めない）。

export type Ir = {
  irVersion: number;
  behaviors: { name: string; from: string[]; onlyIf: string[]; when: Record<string, { does?: string }> }[];
  decisions: Record<string, { rows: Record<string, Record<string, unknown>> }>;
  model?: SpecModel;
};

// 作業場所の中で、依頼文と添付資料を置くディレクトリ
export const TEST_DIR = CONTROL_DIR;
// 本番コードの既定のディレクトリ名
export const SOURCE_DIR = DEFAULT_SOURCE_DIR;

// 対象言語によらないファイル
export const FILES = {
  ir: "ir.json",
  request: "REQUEST.md",
} as const;

// TypeScript を対象とするときの、テスト側のファイル名
export const TS_FILES = {
  contract: "adapter.contract.ts",
  adapter: "adapter.ts",
  verify: "verify.ts",
} as const;

export function specHash(ir: Ir): string {
  return `sha256:${createHash("sha256").update(stableStringify(ir)).digest("hex")}`;
}

function header(ir: Ir): string {
  return `// Code generated by clp. DO NOT EDIT.\n// ir-version: ${ir.irVersion}\n// spec-hash:  ${specHash(ir)}\n`;
}

const union = (values: readonly string[]) => values.map((value) => JSON.stringify(value)).join(" | ") || "never";

function fieldType(schema: FieldSchema): string {
  if (schema === "integer") return "number";
  if (typeof schema === "string") return schema;
  return Array.isArray(schema) ? union(schema) : "number";
}

function shape(fields: Record<string, FieldSchema>): string {
  const entries = Object.keys(fields).sort().map((key) => `${key}: ${fieldType(fields[key])}`);
  return entries.length === 0 ? "{}" : `{ ${entries.join("; ")} }`;
}

const members = (lines: string[]) => (lines.length === 0 ? "{}" : `{\n${lines.map((line) => `    ${line};`).join("\n")}\n  }`);

// アダプターの契約。エージェントが読むのでコメントは英語。
export function generateContract(ir: Ir): string {
  const model = requireModel(ir);
  const behaviors = [...ir.behaviors].sort((a, b) => (a.name < b.name ? -1 : 1));
  const queries = Object.keys(model.queries).sort().map((name) => `${name}(): ${fieldType(model.queries[name])}`);
  const effects = Object.keys(model.effects).sort().map((name) => `${name}(payload: ${shape(model.effects[name])}): void`);

  return `${header(ir)}
export type StateName = ${union(model.states)};

/** One command to execute: its name and the input that goes with it. */
export type Command =
${behaviors.map((b) => `  | { name: ${JSON.stringify(b.name)}; input: ${shape(model.commands[b.name] ?? {})} }`).join("\n")};

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   */
  queries: ${members(queries)};
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: ${members(effects)};
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to \`ports\`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
`;
}

// アダプターの雛形が出すエラー。本番コードの「未実装」とは別の文言にする。
// 同じだと、配線の段階が何も書かなくても「未実装で失敗した」ように見えて、赤の確認を通ってしまう
export const ADAPTER_NOT_WRITTEN = "the adapter is not written yet";

export function generateAdapterSkeleton(ws: Workspace): string {
  const methods = ["setupIsolation(ports)", "teardownIsolation()", "executeCommand(command)", "getCurrentState()"];
  return `import type { TargetSystemAdapter } from "${importPath(ws.paths.adapter, ws.paths.contract)}";

// Import the production code from ${dirFrom(ws.paths.adapter, ws.src)} and forward each call to it. No business logic here.
export const adapter: TargetSystemAdapter = {
${methods.map((method) => `  async ${method} {\n    throw new Error("${ADAPTER_NOT_WRITTEN}");\n  },`).join("\n")}
};
`;
}

export function generateVerify(ir: Ir, ws: Workspace, specsDir: string): string {
  const specs = relative(testsDirOf(ws), specsDir).split(sep).join("/");
  return `${header(ir)}
import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./${posix.basename(ws.paths.adapter)}";

await runPbt({ specs: fileURLToPath(new URL(${JSON.stringify(specs + "/")}, import.meta.url)), component: ${JSON.stringify(ws.component)}, adapter });
`;
}

export function requireModel(ir: Ir): SpecModel {
  if (!ir.model) throw new Error("仕様にコンポーネントがありません（component(...) を export してください）");
  return ir.model;
}
