import { createHash } from "node:crypto";
import { relative, sep } from "node:path";
import type { FieldSchema } from "@aac/core";
import { stableStringify } from "./extract.ts";
import type { SpecModel } from "./extract.ts";

// テスト側ファイルの生成。フレームワークが生成するのはテスト側だけで、本番コードには何も置かない。
// 出力は IR だけから決まる（日時・CLI バージョンは埋めない）。

export type Ir = {
  irVersion: number;
  behaviors: { name: string; from: string[]; preconditions: string[]; transitions: Record<string, unknown> }[];
  decisions: Record<string, { bound: boolean; rows: Record<string, unknown> }>;
  model?: SpecModel;
};

export const TEST_DIR = "aac";
export const SOURCE_DIR = "src";

export const FILES = {
  ir: "ir.json",
  contract: "adapter.contract.ts",
  adapter: "adapter.ts",
  verify: "verify.ts",
  request: "REQUEST.md",
} as const;

export function specHash(ir: Ir): string {
  return `sha256:${createHash("sha256").update(stableStringify(ir)).digest("hex")}`;
}

function header(ir: Ir): string {
  return `// Code generated by aac. DO NOT EDIT.\n// ir-version: ${ir.irVersion}\n// spec-hash:  ${specHash(ir)}\n`;
}

const union = (values: readonly string[]) => values.map((value) => JSON.stringify(value)).join(" | ") || "never";

function fieldType(schema: FieldSchema): string {
  if (schema === "integer") return "number";
  if (typeof schema === "string") return schema;
  return Array.isArray(schema) ? union(schema) : "number";
}

function shape(fields: Record<string, FieldSchema>): string {
  const entries = Object.keys(fields).sort().map((key) => `${key}: ${fieldType(fields[key])}`);
  return entries.length === 0 ? "{}" : `{ ${entries.join("; ")} }`;
}

const members = (lines: string[]) => (lines.length === 0 ? "{}" : `{\n${lines.map((line) => `    ${line};`).join("\n")}\n  }`);

// アダプターの契約。エージェントが読むのでコメントは英語。
export function generateContract(ir: Ir): string {
  const model = requireModel(ir);
  const behaviors = [...ir.behaviors].sort((a, b) => (a.name < b.name ? -1 : 1));
  const queries = Object.keys(model.queries).sort().map((name) => `${name}(): ${fieldType(model.queries[name])}`);
  const commands = Object.keys(model.commands).sort().map((name) => `${name}(payload: ${shape(model.commands[name])}): void`);

  return `${header(ir)}
export type StateName = ${union(model.states)};

/** One action to execute: its name and the input that goes with it. */
export type Action =
${behaviors.map((b) => `  | { name: ${JSON.stringify(b.name)}; input: ${shape(model.actions[b.name] ?? {})} }`).join("\n")};

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between actions: ask when needed, do not cache.
   */
  queries: ${members(queries)};
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  commands: ${members(commands)};
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to \`ports\`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one action. A trial executes several actions in sequence on the same system. */
  executeAction(action: Action): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
`;
}

export function generateAdapterSkeleton(): string {
  const methods = ["setupIsolation(ports)", "teardownIsolation()", "executeAction(action)", "getCurrentState()"];
  return `import type { TargetSystemAdapter } from "./${FILES.contract}";

// Import the production code from ../${SOURCE_DIR}/ and forward each call to it. No business logic here.
export const adapter: TargetSystemAdapter = {
${methods.map((method) => `  async ${method} {\n    throw new Error("not implemented");\n  },`).join("\n")}
};
`;
}

export function generateVerify(ir: Ir, testDir: string, specsDir: string): string {
  const specs = relative(testDir, specsDir).split(sep).join("/");
  return `${header(ir)}
import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./${FILES.adapter}";

await runPbt({ specs: fileURLToPath(new URL(${JSON.stringify(specs + "/")}, import.meta.url)), adapter });
`;
}

export function requireModel(ir: Ir): SpecModel {
  if (!ir.model) throw new Error("仕様にコンポーネントがありません（defineComponent(...).cases(...) を export してください）");
  return ir.model;
}
