import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { isDescription, isFragment } from "@clp/core";
import type { CommandShape, Layer1 } from "@clp/core";
import { assetsFor, mergeAssets } from "./assets.ts";
import type { Asset } from "./assets.ts";
import { boundaryOf } from "./extract.ts";
import type { SpecInput, SpecModel } from "./extract.ts";
import { scrubEnv } from "./gates.ts";
import { TEST_DIR, FILES } from "./generate.ts";
import { DRAFT_SUFFIX, STAMP, layer1Hash, listComponents, loadSpecs, stampIn } from "./loader.ts";
import { ASSETS_DIR, renderAssets } from "./request.ts";
import type { Difference } from "./runtime.ts";
import type { ImplementationStrategy } from "./strategy.ts";

// 解釈 (Layer 2) を LLM に導かせる。実装のループとは別の、仕様を書く人のための工程。
// 人が書くのは Layer 1 だけ。解釈は、Layer 1 が構造として書かなかった分 (構造) と、名前の意味 (関数) を持つ。
//
// 解釈は採点の正解なので、LLM が導いたものをそのまま正解にはしない:
//   - 解釈がまだ無ければ、雛形から書かせる。すでにあって、Layer 1 の変更で古くなっていれば、
//     いまの解釈を出発点にして、合わなくなった所だけを直させる。いまの Layer 1 に合っていれば、何もしない
//   - 導いたものは <名前>.interpretation.draft.ts に書き出す。ローダーは既定で *.draft.ts を読まないので、
//     人が確定する (accept) まで、検証には使われない
//   - 機械的に確かめられること（型エラー、Layer 1 の書き換え、参照の誤り、条件の衝突、不変条件、値の型）は、
//     書き出す前に検査して差し戻す
//   - sessions が 2 以上のときは、ほかのセッションにも、同じ境界のもとで独立に解釈させ、1つ目と同じコマンド列で実行して比べる。
//     食い違う所は、Layer 1 の記述があいまいな所である。人はそこを読んで、Layer 1 を詳しくする
// 記述と解釈が合っているかを最後に決めるのは、人である。

export type InterpretOptions = {
  specs: string;
  // 解釈するコンポーネントの名前。省略時は、解釈が無いか古くなっている最初のもの（名前順）
  component?: string;
  strategy: ImplementationStrategy;
  // 独立に解釈させるセッションの数。2 以上にすると、1つ目とほかのそれぞれとの食い違いを報告する
  sessions?: number;
  // 依頼に添付する資料（用語集など）。コンポーネントの assets に宣言したものに追加される
  assets?: Asset[];
  maxAttempts?: number;
  log?: (line: string) => void;
};

export type Question = { line: number; text: string };
export type InterpretResult =
  | { status: "up-to-date" }
  | {
      status: "interpreted" | "failed";
      component: string;
      draft: string;
      attempts: number;
      problems?: string;
      // 下書きが、すでにある解釈を直したものであるとき、その元のファイル
      updates?: string;
      // 解釈した LLM が残した疑問点 (// REVIEW:)
      questions: Question[];
      // すでにある解釈を直したとき: 構造が変わったもの（コマンド名と、model.data などの語彙の項目）と、変わらなかったものの数。
      // 意味の関数の変更は含まない
      changed?: string[];
      unchanged?: number;
      // ほかのセッションの解釈との食い違い（sessions が 2 以上のとき）。"failed" は、その解釈を導けなかった
      comparisons?: Comparison[];
    };

export type Comparison = { session: number; status: "compared" | "failed"; differences: Difference[] };

// 検査と比較は、別プロセスの clp で行う
const CLP = join(import.meta.dirname, "../bin/clp.ts");
const SPEC_DIR = "spec";
const REQUEST = `${TEST_DIR}/${FILES.request}`;
const INTERPRETATION = ".interpretation";

const header = (hash: string) => `// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
${STAMP}${hash}
`;
const stripHeader = (text: string) => text.replace(/^\/\/ Code generated by clp interpret\.[^\n]*\n/, "").replace(new RegExp(`^${STAMP}[^\n]*\n`), "");

const quote = (name: string) => JSON.stringify(name);
const TODO = `{\n        throw new Error("TODO");\n      }`;
const literal = (value: unknown, indent: string) => JSON.stringify(value, null, 2).split("\n").join(`\n${indent}`);

// Layer 1 に書かれたコマンド（文だけなら description だけを持つ）。コマンドが並べられていなければ undefined
function sketched(layer1: Layer1): Record<string, CommandShape> | undefined {
  const commands = layer1.commands;
  if (commands === undefined || isDescription(commands)) return undefined;
  return Object.fromEntries(
    Object.entries(commands).map(([name, part]) => [name, isDescription(part) ? { description: part.$description } : isFragment(part) ? part.$fragment : {}]),
  );
}

// Layer 1 に出てくる条件の文（決定表の行、onlyIf、when のキー）
function sentences(layer1: Layer1): string[] {
  const found = new Set<string>();
  for (const table of Object.values(layer1.decisions ?? {})) for (const row of Object.keys(table)) found.add(row);
  for (const shape of Object.values(sketched(layer1) ?? {})) {
    for (const name of [...(shape.onlyIf ?? []), ...Object.keys(shape.when ?? {})]) found.add(name);
  }
  found.delete("otherwise");
  return [...found].sort();
}

const structured = (value: unknown) => value !== undefined && !isDescription(value);
// 項目に書かれた部品（文だけなら description だけを持つ）
const partsOf = (entry: unknown): CommandShape => (isDescription(entry) ? { description: entry.$description } : isFragment(entry) ? entry.$fragment : {});

// ほかの解釈に渡す語彙からは、しきい値 (around) を除く。1つ目が文から読み取った数値が、そこから伝わってしまうため
const withoutThresholds = <T>(value: T): T =>
  JSON.parse(JSON.stringify(value, (key, item) => (key === "around" ? undefined : item))) as T;

// 出発点: Layer 1 に書かれたコマンドと名前を並べ、中身は空にしておく。
// pinned があれば（2つ目の解釈）、境界（状態・コマンドの入力・問い合わせ・副作用）を、それで埋めておく
function skeleton(layer1: Layer1, componentFile: string, exportName: string, pinned?: SpecModel): string {
  const groups: string[] = [];
  const todo = (key: string, what: string) => groups.push(`    // TODO: ${key} — ${what}`);
  if (!structured(layer1.states)) pinned ? groups.push(`    states: ${literal(pinned.states, "    ")},`) : todo("states", "the state names");
  if (layer1.init === undefined) pinned ? groups.push(`    init: ${quote(pinned.init)},`) : todo("init", "the initial state");

  // 語彙のまとまり: Layer 1 が項目を並べていれば、足りない部品だけを、項目ごとに。並べていなければ、まとまりごと
  const WHAT = {
    data: "what the component remembers between commands, each as { type } (omit if nothing)",
    queries: "what it asks its dependencies, each as { input?, output } (omit if nothing)",
    effects: "the effects it has on its dependencies, each as { input? } (omit if none)",
  };
  const fromPinned = (key: "queries" | "effects", name: string, lacks: (part: string) => boolean): Record<string, unknown> => {
    const entry: Record<string, unknown> = {};
    const fields = key === "queries" ? pinned!.queries[name]?.input : pinned!.effects[name];
    if (lacks("input") && Object.keys(fields ?? {}).length > 0) entry.input = fields;
    if (key === "queries" && lacks("output")) entry.output = pinned!.queries[name]?.output;
    return entry;
  };
  for (const key of ["data", "queries", "effects", "calculations"] as const) {
    const given = layer1[key];
    if (given === undefined || isDescription(given)) {
      if (key === "calculations") continue;
      if (pinned && key !== "data") {
        const all = Object.fromEntries(Object.keys(pinned[key]).map((name) => [name, fromPinned(key, name, () => true)]));
        groups.push(`    ${key}: ${literal(all, "    ")},`);
      } else todo(key, WHAT[key]);
      continue;
    }
    const lines: string[] = [];
    for (const [name, written] of Object.entries(given)) {
      const shape = partsOf(written);
      const note = shape.description ? `      // ${shape.description}\n` : "";
      if (key === "data" && shape.type === undefined) lines.push(`${note}      ${name}: { type: "TODO" },`);
      if (key === "calculations" && shape.output === undefined) lines.push(`${note}      ${name}: { output: "TODO" },`);
      if (key === "queries" || key === "effects") {
        const lacks = (part: string) => (shape as Record<string, unknown>)[part] === undefined;
        if (pinned) {
          const entry = fromPinned(key, name, lacks);
          if (Object.keys(entry).length > 0) lines.push(`      ${name}: ${literal(entry, "      ")},`);
        } else if (key === "queries" && lacks("output")) lines.push(`${note}      ${name}: { output: "TODO" },`);
        else if (lacks("input") && shape.description !== undefined) lines.push(`${note}      ${name}: {},`);
      }
    }
    if (lines.length > 0) groups.push(`    ${key}: {\n${lines.join("\n")}\n    },`);
  }
  const calculations = layer1.calculations;

  const known = sketched(layer1);
  const names = known ? Object.keys(known) : Object.keys(pinned?.commands ?? {});
  const commands = names.map((name) => {
    const shape = known?.[name] ?? {};
    const notes = [shape.description, shape.does].filter((text): text is string => text !== undefined).map((text) => `      // ${text}\n`).join("");
    const fixed = pinned && shape.input === undefined ? `input: ${literal(pinned.commands[name] ?? {}, "      ")}, ` : "";
    if (!shape.when) return `${notes}      ${name}: {${fixed ? ` ${fixed}` : ""}},`;
    const branches: Record<string, { does?: string }> = { ...shape.when, ...(shape.when.otherwise ? {} : { otherwise: {} }) };
    const cases = Object.entries(branches)
      .map(([condition, outcome]) => `${outcome.does ? `          // ${outcome.does}\n` : ""}          ${quote(condition)}: {},`)
      .join("\n");
    return `${notes}      ${name}: {\n        ${fixed}when: {\n${cases}\n        },\n      },`;
  });
  if (known || pinned) groups.push(`    commands: {\n${commands.join("\n")}\n    },`);
  else groups.push("    // TODO: commands — every command, with its input, where it applies, where it leads, and what it does\n    commands: {},");

  const meaning = (key: string, entries: string[]) => (entries.length === 0 ? "" : `    ${key}: {\n${entries.join("\n")}\n    },\n`);
  const declared = calculations === undefined || isDescription(calculations) ? {} : calculations;
  return `import { calculate, decide, interpretation, ref } from "@clp/core";
import { ${exportName} } from "./${componentFile}";

export const Interpretation = interpretation(${exportName}, {
  // Structure: what Layer 1 left as prose, as declarations. No functions.
  structure: {
${groups.join("\n")}
  },

  // Meaning: what each name refers to, as functions.
  meanings: {
    conditions: {
${sentences(layer1).map((name) => `      ${quote(name)}: (state) => ${TODO},`).join("\n")}
    },
${meaning("calculations", Object.entries(declared).map(([name, entry]) => `      // ${partsOf(entry).description ?? ""}\n      ${name}: (state) => ${TODO},`))}${meaning("invariants", (layer1.invariants ?? []).map((name) => `      ${quote(name)}: (state) => ${TODO},`))}  },
});
`;
}

// update: すでにある解釈を、Layer 1 の変更に合わせて直す。pinned: 2つ目の解釈（境界は固定）
function request(draftFile: string, componentFile: string, attempt: number, assets: Asset[], problems: string | undefined, mode: { update: boolean; pinned: boolean }) {
  const { update, pinned } = mode;
  return `# ${update ? "Update" : "Write"} the interpretation of a specification (attempt ${attempt})

The files under \`${SPEC_DIR}/\` are a specification. \`${componentFile}\` is **Layer 1**, written by a person: it describes
a component partly as structure and partly as prose (\`description("...")\`, \`does("...")\`, condition sentences). ${
    update
      ? `The **interpretation** says what the prose means. Layer 1 has changed since the interpretation was
written. Your task is to bring the interpretation up to date. A person will review what you changed before it is used.`
      : `Your
task is to write the **interpretation** (Layer 2): everything Layer 1 left as prose, turned into structure, plus the
meaning of every sentence as a function. A person will review it before it is used.`
  }

## What to write

Edit \`${SPEC_DIR}/${draftFile}\`, and only that file. ${
    update
      ? `It holds the interpretation as it was. **Change only what Layer 1 now requires**: add what is missing,
remove what is no longer used, and correct an entry only if the prose it interprets changed. Leave every other
entry exactly as it is, including its formatting. Any problems the current interpretation has are listed at the
end of this request.`
      : "It lists what Layer 1 already names, with empty\nplaceholders, and marks what is missing with `TODO`."
  } It has two parts.${
    pinned
      ? `

**The vocabulary is fixed.** \`states\`, \`init\`, \`queries\` (with their \`input\` and \`output\`), \`effects\`
(with their \`input\`), the command names, and each command's \`input\` are already filled in where Layer 1
does not give them. Do not change them. Everything else is yours to
decide from the prose.

**Take the other reading.** Another interpreter has already written the most obvious reading of this
specification. Your interpretation will be compared with it, to show the author where the prose is ambiguous.
So wherever the prose leaves something unstated, or can reasonably be read in more than one way, choose a
reading that is **defensible but not the most obvious one** (a different condition, a different number, a
different resulting state, an effect performed or not), and mark it with \`// REVIEW:\`. Where the prose is
clear, follow it exactly: a difference that the prose does not allow is noise.`
      : ""
  }

### 1. \`structure\`: declarations, no functions

**You cannot override what Layer 1 wrote as structure.** Where Layer 1 gives states, an input, \`from\`, \`onlyIf\`,
a \`goTo\`, or the cases of a \`when\`, do not repeat or change it; write only what is missing.

- Vocabulary. Layer 1 gives each group (\`states\`, \`data\`, \`queries\`, \`effects\`, \`calculations\`) either
  as prose, or as a list of entries, each of which may itself be prose or parts.
  - A group given as prose or not at all: write it. \`states\` is an array of names and \`init\` one of them.
    The other groups are \`{ name: { ...parts } }\`.
  - A group given as a list of entries: do not add entries (except to \`calculations\`); for each entry, write
    only the parts Layer 1 does not give.
  - The parts: \`data\` (what the component remembers between commands; everything is unset at the start):
    \`{ type }\`. \`queries\` (what it asks its dependencies: a clock, a setting, an external service's
    response): \`{ output }\` for the type of the answer, plus \`{ input: { field: type } }\` if it is a question
    about something. \`effects\` (what it does to its dependencies): \`{ input: { field: type } }\` for what it
    carries, or \`{}\`. \`calculations\`: \`{ is: "<how it is computed>", output }\`; for one Layer 1 describes in
    prose, only \`{ output }\`. You may also add \`invariants\` (sentences that must hold after every command).
- Field types: \`"boolean"\`, \`"integer"\`, \`"number"\`, \`"string"\`, an array of allowed strings, or
  \`{ type: "integer", min, max, around: [thresholds] }\`. Use whole numbers for money. The names of \`data\`
  fields, queries without input, command inputs, and the names given in \`asks\` share one namespace and must
  not collide (inputs, and \`asks\` names, of different commands may).
- \`commands\`: one entry for **every** command, even if you add nothing (\`{}\`). An entry may hold, where
  Layer 1 does not: \`input\`, \`from\` (the states in which the command can be executed), \`onlyIf\` (condition
  sentences that must hold), \`asks\` (below), and the outcome:
  - \`goTo\`: the resulting state. **Omit it when the state does not change.**
  - \`effects\`: the effects to perform, in order, each as \`{ EffectName: { field: value, ... } }\`. Add
    \`when: ...\` to perform an effect only sometimes.
  - \`set\`: the data to store, as \`{ field: value }\`.
  - If the command branches, put the outcomes under \`when: { "<condition sentence>": { ... }, otherwise: { ... } }\`
    instead. If Layer 1 already lists the cases, write one entry for each of them (you may add only
    \`otherwise\`). \`otherwise\` is mandatory.
  - For a command Layer 1 only describes in prose, you may add \`does: "<what happens>"\` to an outcome.

A query that takes an \`input\` cannot be read by its name: the command must say what it asks about.
\`asks: { answerName: { queryName: { field: value } } }\` asks that query with that input and names the answer.
The input values are constants, \`ref.input(...)\` or \`ref.data(...)\`. Functions read the answer as
\`state.answerName\`, and the structure refers to it as \`ref.query("answerName")\`. The implementation is
tested against this: it may ask that query only with the inputs listed here.

A value is a constant or a reference:

- \`ref.input("field")\`: the command's input
- \`ref.data("field")\`: remembered data
- \`ref.query("name")\`: the answer of a query without input, or an answer named in the command's \`asks\`
- \`ref.decision("table", "column")\`: the value of a decision table's column in the row that applies. A cell
  written as \`null\` has no value in that row, so a reference to it must only be reached when another row applies
  (for example behind a \`when\`).
- \`ref.calculation("name")\`: the result of a calculation

An effect's \`when\` is either a boolean reference (\`ref.decision(...)\`, \`ref.query(...)\`, \`ref.data(...)\`, or
\`ref.was("STATE", ...)\` for "the state before the command was one of these"), or a new condition sentence in
natural language, which you must then also define under \`meanings.conditions\`. Prefer a reference when one fits.

### 2. \`meanings\`: functions

- \`conditions\`: one function per condition sentence (decision-table rows, \`onlyIf\`, the keys of \`when\`, and
  the \`when\` sentences of effects), returning a boolean. \`calculations\`: one per calculation, returning a value
  of its type. \`invariants\`: one per invariant, returning a boolean that must always be true.
- Conditions and calculations receive \`state\` with: \`status\` (the current state name); the remembered data,
  each possibly \`undefined\` before it is set; the answers of queries without input; and the inputs and the
  \`asks\` answers of the command being executed, \`undefined\` during other commands. \`invariants\` functions receive only \`status\` and the remembered data.
- Inside a function, \`decide(Component, "table", state)\` gives the row of a decision table that applies, and
  \`calculate(Component, "name", state)\` gives the result of another calculation.

## Rules

- ${pinned ? "Layer 1 is the specification; do not add anything it does not state." : "**Write the most literal reading of the prose.** Layer 1 is the specification; do not add anything it does\n  not state."} If a sentence can reasonably be read in more than one way, pick one and put a comment starting with
  \`// REVIEW:\` on the line above it explaining the doubt. Those comments are reported to the author, who will
  then make Layer 1 more precise.
- Conditions that label the rows of the same decision table, or the cases of the same command, must never be
  true at the same time (\`otherwise\` covers "none of them").
- \`onlyIf\` (and \`from\`) put a situation **outside** the specification: nothing about it is tested, and
  the production code need not handle it. Use them only for situations that cannot arise or that someone else
  rules out. When the prose says something is refused, not allowed, or has no effect, write that as an outcome
  (a case under \`when\` with no \`goTo\` and no effects), so that the refusal itself is verified.
- Calculations over money use whole numbers; apply the rounding the description states.
- Do not change any other file, and do not read anything outside this directory.

## How the interpretation is checked

After you finish, the file is type-checked, and the specification is run on its own over many random sequences
of commands. The interpretation is rejected if it has a type error, if it overrides structure written in
Layer 1, if a command or a case is missing, if a reference does not fit the field it is used for, if a name is
left without a meaning, if two conditions of the same table or command hold at once, if an invariant is broken,
or if a value does not fit its declared type. Passing this check does not mean the interpretation is right; that
is what the review is for.
${renderAssets(assets)}${problems ? `\n## ${update && attempt === 1 ? "Problems with the current interpretation" : "Problems found in the previous attempt"}\n\n\`\`\`\n${problems}\n\`\`\`\n` : ""}`;
}

// 仕様を読み込み、型チェックと仕様の検査にかける。別プロセスで行う（LLM が書いたファイルを、このプロセスに読み込まない）。
// drafts が true なら、下書きを使って検査する。見るのは指定したコンポーネントだけ。通れば IR を返す
type CheckedIr = { model?: SpecModel; behaviors?: { name: string }[] };
function check(specsDir: string, drafts: boolean, component: string): { ir?: CheckedIr; problems?: string } {
  const run = spawnSync(process.execPath, [CLP, "compile", specsDir, "--component", component, ...(drafts ? ["--drafts"] : [])], {
    encoding: "utf8",
    timeout: 120_000,
  });
  if (run.status === 0) return { ir: JSON.parse(run.stdout) };
  const problems = [process.cwd(), specsDir]
    .reduce((output, path) => output.split(path).join("."), `${run.stderr ?? ""}${run.error?.message ?? ""}`)
    .split("\n")
    .filter((line) => !line.includes("ExperimentalWarning") && !line.includes("--trace-warnings"))
    .join("\n")
    .trim()
    .slice(-3000);
  // 検査に落ちても、IR が作れていれば返す（古くなった解釈の構造を、直したあとのものと比べるため）
  let ir: CheckedIr | undefined;
  try {
    ir = JSON.parse(run.stdout) as CheckedIr;
  } catch {
    ir = undefined;
  }
  return { ...(ir?.model ? { ir } : {}), problems: problems || "The check failed without a message." };
}

// 2つの IR の構造を、コマンドごと・語彙の項目ごとに比べる
function structureChanges(before: CheckedIr, after: CheckedIr): { changed: string[]; unchanged: number } {
  const parts = (ir: CheckedIr) =>
    new Map<string, string>([
      ...Object.entries(ir.model ?? {}).map(([key, value]): [string, string] => [`model.${key}`, JSON.stringify(value)]),
      ...(ir.behaviors ?? []).map((behavior): [string, string] => [behavior.name, JSON.stringify(behavior)]),
    ]);
  const [old, now] = [parts(before), parts(after)];
  const names = [...new Set([...old.keys(), ...now.keys()])];
  const changed = names.filter((name) => old.get(name) !== now.get(name));
  return { changed, unchanged: names.length - changed.length };
}

const questionsIn = (text: string): Question[] =>
  text.split("\n").flatMap((line, index) => {
    const match = /\/\/\s*REVIEW:\s*(.*)$/.exec(line);
    return match ? [{ line: index + 1, text: match[1].trim() }] : [];
  });

type Session = {
  specsDir: string;
  // 検査するディレクトリ（1つ目は仕様そのもの、2つ目はその写し）
  target: string;
  component: string;
  componentFile: string;
  draftFile: string;
  start: string;
  hash: string;
  update: boolean;
  pinned?: SpecModel;
  // 何番目のセッションか（1 が、下書きとして残るもの）
  index: number;
  // 作業場所に置かない、確定版のファイル（下書きが置き換えるもの）
  hidden?: string;
  assets: Asset[];
  options: InterpretOptions;
  label: string;
  firstProblems?: string;
};

// 1つのセッション: エージェントに下書きを書かせ、検査に通るまで差し戻す
async function session(s: Session): Promise<{ ok: boolean; attempts: number; problems?: string; ir?: CheckedIr }> {
  const { specsDir, target, draftFile, options } = s;
  const log = options.log ?? (() => {});
  const maxAttempts = options.maxAttempts ?? 3;
  const hiddenPaths = [...new Set([process.cwd(), specsDir, target])];
  // 作業場所には、ほかの下書きと、この下書きが置き換える確定版は置かない（同じ export が2つあると紛らわしい）
  const specFiles = (readdirSync(specsDir, { recursive: true }) as string[]).filter(
    (file) => file.endsWith(".ts") && !file.endsWith(DRAFT_SUFFIX) && file !== s.hidden,
  );
  let problems = s.firstProblems;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const dir = mkdtempSync(join(realpathSync(tmpdir()), "clp-"));
    let ir: CheckedIr | undefined;
    try {
      const originals: Record<string, string> = {};
      for (const file of specFiles) {
        originals[file] = readFileSync(join(specsDir, file), "utf8");
        mkdirSync(dirname(join(dir, SPEC_DIR, file)), { recursive: true });
        writeFileSync(join(dir, SPEC_DIR, file), originals[file]);
      }
      const previous = join(target, draftFile);
      // 2回目からは、前回の試行の成果から始める
      writeFileSync(join(dir, SPEC_DIR, draftFile), existsSync(previous) && attempt > 1 ? stripHeader(readFileSync(previous, "utf8")) : s.start);
      mkdirSync(join(dir, TEST_DIR), { recursive: true });
      for (const asset of s.assets) {
        if (asset.kind !== "file") continue;
        mkdirSync(dirname(join(dir, ASSETS_DIR, asset.name)), { recursive: true });
        writeFileSync(join(dir, ASSETS_DIR, asset.name), asset.content);
      }
      writeFileSync(join(dir, REQUEST), request(draftFile, s.componentFile, attempt, s.assets, problems, { update: s.update, pinned: s.pinned !== undefined }));

      log(`[${s.label} #${attempt}] ${options.strategy.name} (in ${dir})`);
      await options.strategy.run({ dir, phase: s.index === 1 ? "interpretation" : `interpretation-${s.index}`, attempt, env: scrubEnv(process.env, hiddenPaths) });

      // 取り出すのは下書きだけ。仕様のファイルを書き換えていたら差し戻す
      const changed = specFiles.filter(
        (file) => !existsSync(join(dir, SPEC_DIR, file)) || readFileSync(join(dir, SPEC_DIR, file), "utf8") !== originals[file],
      );
      if (!existsSync(join(dir, SPEC_DIR, draftFile))) {
        problems = `${draftFile} is missing.`;
      } else if (changed.length > 0) {
        problems = `Only ${draftFile} may be edited, but these files were changed: ${changed.join(", ")}`;
      } else {
        writeFileSync(previous, header(s.hash) + stripHeader(readFileSync(join(dir, SPEC_DIR, draftFile), "utf8")));
        const checked = check(target, true, s.component);
        problems = checked.problems;
        ir = checked.ir;
        if (!problems && s.pinned && boundaryOf(withoutThresholds(ir ?? {})) !== boundaryOf({ model: s.pinned })) {
          problems = "The fixed vocabulary was changed. Keep `states`, `init`, `queries`, `effects`, the command names and each command's `input` exactly as they were given.";
        }
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
    log(`[${s.label} #${attempt}] ${problems === undefined ? "ok" : "rejected"}`);
    if (problems === undefined) return { ok: true, attempts: attempt, ir };
  }
  return { ok: false, attempts: maxAttempts, problems };
}

// 解釈のファイルの名前: order.component.ts → order.interpretation.ts
const interpretationFile = (componentFile: string) =>
  join(dirname(componentFile), `${basename(componentFile).replace(/(\.component)?\.ts$/, "")}${INTERPRETATION}.ts`);

export async function interpret(options: InterpretOptions): Promise<InterpretResult> {
  const specsDir = resolve(process.cwd(), options.specs);
  const log = options.log ?? (() => {});

  // コンポーネントを名前順に見て、解釈が要る最初のものを選ぶ。Layer 1 だけを読む
  const names = options.component === undefined ? await listComponents(specsDir) : [options.component];
  if (names.length === 0) throw new Error("仕様にコンポーネントがありません");
  let chosen: { spec: SpecInput; name: string; current?: string; problems?: string; before?: CheckedIr } | undefined;
  for (const name of names) {
    const spec = await loadSpecs(specsDir, { bindings: false, component: name });
    const component = spec.sources?.component;
    if (!component) continue;
    // いま有効な解釈: 下書きがあればそれ、無ければ確定版。Layer 1 に合っていれば、何もしない
    const final = spec.sources?.binding ?? interpretationFile(component.file);
    const draft = final.replace(/\.ts$/, DRAFT_SUFFIX);
    const current = existsSync(join(specsDir, draft)) ? draft : existsSync(join(specsDir, final)) ? final : undefined;
    if (current === undefined) {
      chosen = { spec, name };
      break;
    }
    const checked = check(specsDir, current === draft, name);
    if (checked.problems === undefined) continue;
    chosen = { spec, name, current, problems: checked.problems, before: checked.ir };
    break;
  }
  if (!chosen) return { status: "up-to-date" };

  const { spec, name } = chosen;
  const component = spec.sources!.component!;
  const layer1 = spec.layer1 as Layer1;
  const hash = layer1Hash(layer1);
  const final = spec.sources?.binding ?? interpretationFile(component.file);
  const draftFile = final.replace(/\.ts$/, DRAFT_SUFFIX);
  const update = chosen.current !== undefined;
  const componentFile = basename(component.file);
  const assets = assetsFor(mergeAssets(spec.assets ?? [], options.assets ?? []), "design");
  const updates = update && chosen.current === final ? { updates: join(specsDir, final) } : {};

  const first = await session({
    specsDir,
    target: specsDir,
    component: name,
    componentFile,
    draftFile,
    start: update ? stripHeader(readFileSync(join(specsDir, chosen.current!), "utf8")) : skeleton(layer1, componentFile, component.exportName),
    hash,
    update,
    hidden: final,
    assets,
    options,
    label: "interpretation",
    index: 1,
    firstProblems: chosen.problems,
  });
  const draft = join(specsDir, draftFile);
  const questions = existsSync(draft) ? questionsIn(readFileSync(draft, "utf8")) : [];
  if (!first.ok) return { status: "failed", component: name, draft, attempts: first.attempts, problems: first.problems, questions, ...updates };
  const changes = chosen.before && first.ir ? structureChanges(chosen.before, first.ir) : {};
  const result = { status: "interpreted" as const, component: name, draft, attempts: first.attempts, questions, ...updates, ...changes };
  const sessions = Math.max(1, Math.floor(options.sessions ?? 1));
  if (sessions < 2 || !first.ir?.model) return result;

  // ほかの解釈: 仕様の写しの中で、同じ境界のもとに、独立に導かせる（1つ目の下書きも、ほかの解釈も見せない）。
  // 写しは仕様のとなりに置く（@clp/core を解決できる場所。名前は .tmp で始め、バージョン管理の対象外）
  const comparisons: Comparison[] = [];
  for (let index = 2; index <= sessions; index++) {
    const copy = mkdtempSync(join(dirname(specsDir), ".tmp-clp-interpret-"));
    try {
      for (const file of readdirSync(specsDir, { recursive: true }) as string[]) {
        if (!file.endsWith(".ts") || file === draftFile) continue;
        mkdirSync(dirname(join(copy, file)), { recursive: true });
        cpSync(join(specsDir, file), join(copy, file));
      }
      const vocabulary = withoutThresholds(first.ir.model);
      const other = await session({
        specsDir,
        target: copy,
        component: name,
        componentFile,
        draftFile,
        start: skeleton(layer1, componentFile, component.exportName, vocabulary),
        hash,
        update: false,
        pinned: vocabulary,
        hidden: final,
        assets,
        options,
        label: `interpretation ${index}`,
        index,
      });
      const compared = other.ok
        ? spawnSync(process.execPath, [CLP, "__compare", specsDir, copy, "--component", name], { encoding: "utf8", timeout: 300_000 })
        : undefined;
      if (compared && compared.status !== 0) log(`[compare ${index}] failed: ${(compared.stderr ?? "").trim().slice(-500)}`);
      comparisons.push(
        compared?.status === 0
          ? { session: index, status: "compared", differences: JSON.parse(compared.stdout) as Difference[] }
          : { session: index, status: "failed", differences: [] },
      );
    } finally {
      rmSync(copy, { recursive: true, force: true });
    }
  }
  return { ...result, comparisons };
}

// 確定する: 下書きを確定版に置き換え、いまの Layer 1 のハッシュを記す。
// 下書きが無くても、確定版のハッシュを記し直す（Layer 1 の文を直したが、解釈はそのままでよいと人が判断したとき）
export async function accept(options: { specs: string; component?: string }): Promise<{ accepted: string[]; problems: string[] }> {
  const specsDir = resolve(process.cwd(), options.specs);
  const names = options.component === undefined ? await listComponents(specsDir) : [options.component];
  const accepted: string[] = [];
  const problems: string[] = [];
  for (const name of names) {
    const spec = await loadSpecs(specsDir, { bindings: false, component: name });
    const component = spec.sources?.component;
    if (!component || !spec.layer1) continue;
    const final = spec.sources?.binding ?? interpretationFile(component.file);
    const draft = final.replace(/\.ts$/, DRAFT_SUFFIX);
    const hasDraft = existsSync(join(specsDir, draft));
    if (!hasDraft && !existsSync(join(specsDir, final))) {
      problems.push(`${name}: 解釈がありません（先に clp interpret で導いてください）`);
      continue;
    }
    const source = join(specsDir, hasDraft ? draft : final);
    const text = readFileSync(source, "utf8");
    const hash = layer1Hash(spec.layer1);
    if (!hasDraft && stampIn(text) === hash) continue;
    // 確定する前に、いまの Layer 1 のもとで検査に通ることを確かめる
    writeFileSync(source, header(hash) + stripHeader(text));
    const failed = check(specsDir, hasDraft, name).problems;
    if (failed !== undefined) {
      writeFileSync(source, text);
      problems.push(`${name}: 解釈が、いまの Layer 1 に合いません。clp interpret で導き直してください\n${failed}`);
      continue;
    }
    if (hasDraft) renameSync(source, join(specsDir, final));
    accepted.push(join(specsDir, final));
  }
  return { accepted, problems };
}
