// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:ec51fa25f3e63c6279f3f98fa2bc3aebcb073563a432589b5444b9c3f93e32c9

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./loan.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "loan", adapter });
