// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:ec51fa25f3e63c6279f3f98fa2bc3aebcb073563a432589b5444b9c3f93e32c9

export type StateName = "AVAILABLE" | "ON_LOAN" | "OVERDUE" | "LOST";

/** One command to execute: its name and the input that goes with it. */
export type Command =
  | { name: "Borrow"; input: {} }
  | { name: "DayPasses"; input: { days: number } }
  | { name: "Extend"; input: {} }
  | { name: "Return"; input: {} };

/**
 * What a command answers with. Return it from `executeCommand`; it is compared with the specification.
 * A field typed `| null` is `null` when the command has no value for it. Commands not listed here answer nothing.
 */
export type CommandOutput = {
  Borrow: { dueInDays: number | null; result: "lent" | "refused" };
  Extend: "extended" | "refused";
};

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between commands: ask when needed, do not cache.
   * A query that takes an `input` is a question about that input. Pass on exactly what the production code
   * asked about; a question the specification does not ask in that command makes the test fail.
   */
  queries: {
    booksOnLoan(): number;
    reservedBySomeoneElse(): boolean;
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  effects: {
    DueDateNotice(payload: { daysUntilDue: number }): void;
    LateFeeCharge(payload: { amount: number }): void;
    NextMemberNotice(payload: {}): void;
    ReplacementCharge(payload: {}): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one command. A trial executes several commands in sequence on the same system. */
  executeCommand(command: Command): Promise<CommandOutput[keyof CommandOutput] | void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
