// Code generated by clp. DO NOT EDIT.
// ir-version: 5
// spec-hash:  sha256:1020e3c3cfef5a9e1b181afc1fc20e816bf7d2d3ab80c7ebbae6a1be5c2ab2ae

import { fileURLToPath } from "node:url";
import { runPbt } from "@clp/cli/runtime";
import { adapter } from "./loan.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../specs/", import.meta.url)), component: "loan", adapter });
