// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:a34cc850f459c79d43d15b9eab5ef64dad63782daee8ccec879cfdc210393fb9
import { calculate, component, decide, description, does, emits, from, goTo, input, integer, interpretation, onlyWhen, otherwise, output, ref, responds, set, when } from "@clp/core";
import { Loan } from "./loan.component.ts";

export const Interpretation = interpretation(Loan, {
  data: {
    daysUntilDue: "integer",
  },
  queries: {
    booksOnLoan: integer({ min: 0, max: 10, around: [3] }),
    reservedBySomeoneElse: "boolean",
  },
  effects: {
    DueDateNotice: input({ daysUntilDue: "integer" }),
    LateFeeCharge: input({ amount: "integer" }),
    NextMemberNotice: component(),
    ReplacementCharge: component(),
  },
  calculations: {
    daysUntilDueAfterExtension: component(description("The days until the loan is due, plus the policy's extension days"), output("integer")),
    daysUntilDueAfterDaysPass: component(description("The days until the loan is due, minus the days that pass"), output("integer")),
  },
  invariants: [
    "A loan is overdue exactly when it is past its due date",
  ],
  commands: {
    Borrow: component(
      when("The member already holds at least the policy's maximum number of books, or someone else has reserved the book"),
      otherwise(
        emits("DueDateNotice", { daysUntilDue: ref.decision("policy", "loanDays") }),
        set({ daysUntilDue: ref.decision("policy", "loanDays") }),
        responds({ result: "lent", dueInDays: ref.decision("policy", "loanDays") }),
      ),
    ),
    Extend: component(
      when("The book is reserved by someone else"),
      otherwise(
        emits("DueDateNotice", { daysUntilDue: ref.calculation("daysUntilDueAfterExtension") }),
        set({ daysUntilDue: ref.calculation("daysUntilDueAfterExtension") }),
        responds("extended"),
      ),
    ),
    DayPasses: component(
      when(
        "The book is then past its due date by more than the policy's lost-after days",
        goTo("LOST"),
        emits("ReplacementCharge"),
        set({ daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") }),
      ),
      when(
        "The loan is then past its due date, but not by more than the policy's lost-after days",
        goTo("OVERDUE"),
        set({ daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") }),
      ),
      otherwise(set({ daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") })),
    ),
    Return: component(
      from("ON_LOAN", "OVERDUE"),
      goTo("AVAILABLE"),
      emits("LateFeeCharge", { amount: ref.calculation("lateFee") }, onlyWhen(ref.was("OVERDUE"))),
      emits("NextMemberNotice", onlyWhen(ref.query("reservedBySomeoneElse"))),
      does("The book is returned and becomes available again."),
    ),
  },

  meanings: {
    conditions: {
      "The member already holds at least the policy's maximum number of books, or someone else has reserved the book": (state) =>
        state.booksOnLoan >= decide(Loan, "policy", state).maxBooks || state.reservedBySomeoneElse === true,
      "The book is reserved by someone else": (state) => state.reservedBySomeoneElse === true,
      "The book is then past its due date by more than the policy's lost-after days": (state) =>
        calculate(Loan, "daysUntilDueAfterDaysPass", state) < -decide(Loan, "policy", state).lostAfterDays,
      "The loan is then past its due date, but not by more than the policy's lost-after days": (state) => {
        const daysUntilDue = calculate(Loan, "daysUntilDueAfterDaysPass", state);
        return daysUntilDue < 0 && daysUntilDue >= -decide(Loan, "policy", state).lostAfterDays;
      },
    },
    calculations: {
      lateFee: (state) => {
        const policy = decide(Loan, "policy", state);
        const daysPastDue = Math.max(0, -(state.daysUntilDue ?? 0));
        return Math.min(daysPastDue * policy.feePerDay, policy.feeCap);
      },
      daysUntilDueAfterExtension: (state) =>
        (state.daysUntilDue ?? 0) + decide(Loan, "policy", state).extensionDays,
      daysUntilDueAfterDaysPass: (state) => (state.daysUntilDue ?? 0) - (state.days ?? 0),
    },
    invariants: {
      "A loan is overdue exactly when it is past its due date": (state) => {
        if (state.status === "ON_LOAN") return state.daysUntilDue !== undefined && state.daysUntilDue >= 0;
        if (state.status === "OVERDUE") return state.daysUntilDue !== undefined && state.daysUntilDue < 0;
        return true;
      },
    },
  },
});
