// Code generated by clp interpret. Do not edit: make the component (Layer 1) more precise and run it again.
// layer1: sha256:0e440244e92b61cd22f8fec931899a7b204f4821041652fd0ad1e3aca2acae51
import { calculate, decide, interpretation, ref } from "@clp/core";
import { Loan } from "./loan.component.ts";

export const Interpretation = interpretation(Loan, {
  // Structure: what Layer 1 left as prose, as declarations. No functions.
  structure: {
    data: {
      // The number of days that remain until the book is due, counted down by DayPasses (negative once the due
      // date has passed). It has no upper bound because Layer 1 does not limit how many times a loan can be extended.
      daysUntilDue: { type: "integer" },
    },
    queries: {
      // Layer 1 does not identify the member, so this is asked without input, about "the member" of this loan.
      // REVIEW: the upper bound of 10 is only a range for the type, not a rule, and the threshold 3 only mirrors
      // the policy's current maximum (the rule itself reads the policy table).
      booksOnLoan: { output: { type: "integer", min: 0, max: 10, around: [3] } },
      reservedBySomeoneElse: { output: "boolean" },
    },
    effects: {
      DueDateNotice: { input: { daysUntilDue: "integer" } },
      LateFeeCharge: { input: { amount: "integer" } },
      NextMemberNotice: {},
      ReplacementCharge: {},
    },
    calculations: {
      daysUntilDueAfterExtension: { is: "The days until the loan is due, plus the policy's extension days", output: "integer" },
      daysUntilDueAfterDaysPass: { is: "The days until the loan is due, minus the days that pass", output: "integer" },
    },
    invariants: [
      "A loan is overdue exactly when it is past its due date",
    ],
    commands: {
      Borrow: {
        when: {
          // The borrowing is refused; nothing changes.
          "The member already holds at least the policy's maximum number of books, or someone else has reserved the book": {},
          // The book is due in the policy's loan days. The member is told the due date.
          "otherwise": {
            effects: [{ DueDateNotice: { daysUntilDue: ref.decision("policy", "loanDays") } }],
            set: { daysUntilDue: ref.decision("policy", "loanDays") },
          },
        },
      },
      Extend: {
        when: {
          // The extension is refused; nothing changes.
          "The book is reserved by someone else": {},
          // The due date moves later by the policy's extension days, counted from the current due date. The member is told the new due date. A loan can be extended any number of times.
          "otherwise": {
            effects: [{ DueDateNotice: { daysUntilDue: ref.calculation("daysUntilDueAfterExtension") } }],
            set: { daysUntilDue: ref.calculation("daysUntilDueAfterExtension") },
          },
        },
      },
      // The given number of days passes. A loan past its due date (fewer than zero days remain) becomes overdue. A book past its due date by more than the policy's lost-after days is considered lost, and the member is charged for a replacement, once.
      DayPasses: {
        when: {
          "The book is then past its due date by more than the policy's lost-after days": {
            goTo: "LOST",
            effects: [{ ReplacementCharge: {} }],
            set: { daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") },
          },
          "The loan is then past its due date, but not by more than the policy's lost-after days": {
            goTo: "OVERDUE",
            set: { daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") },
          },
          "otherwise": {
            set: { daysUntilDue: ref.calculation("daysUntilDueAfterDaysPass") },
          },
        },
      },
      // A book on loan or overdue can be returned; a lost book cannot. Returning an overdue book is charged the late fee. Then, if someone else has reserved the book, the next member waiting is notified.
      Return: {
        from: ["ON_LOAN", "OVERDUE"],
        goTo: "AVAILABLE",
        effects: [
          { LateFeeCharge: { amount: ref.calculation("lateFee") }, when: ref.was("OVERDUE") },
          { NextMemberNotice: {}, when: ref.query("reservedBySomeoneElse") },
        ],
        does: "The book is returned and becomes available again.",
      },
    },
  },

  // Meaning: what each name refers to, as functions.
  meanings: {
    conditions: {
      "The member already holds at least the policy's maximum number of books, or someone else has reserved the book": (state) =>
        state.booksOnLoan >= decide(Loan, "policy", state).maxBooks || state.reservedBySomeoneElse === true,
      "The book is reserved by someone else": (state) => state.reservedBySomeoneElse === true,
      "The book is then past its due date by more than the policy's lost-after days": (state) =>
        calculate(Loan, "daysUntilDueAfterDaysPass", state) < -decide(Loan, "policy", state).lostAfterDays,
      "The loan is then past its due date, but not by more than the policy's lost-after days": (state) => {
        const daysUntilDue = calculate(Loan, "daysUntilDueAfterDaysPass", state);
        return daysUntilDue < 0 && daysUntilDue >= -decide(Loan, "policy", state).lostAfterDays;
      },
    },
    calculations: {
      lateFee: (state) => {
        const policy = decide(Loan, "policy", state);
        const daysPastDue = Math.max(0, -(state.daysUntilDue ?? 0));
        return Math.min(daysPastDue * policy.feePerDay, policy.feeCap);
      },
      daysUntilDueAfterExtension: (state) =>
        (state.daysUntilDue ?? 0) + decide(Loan, "policy", state).extensionDays,
      daysUntilDueAfterDaysPass: (state) => (state.daysUntilDue ?? 0) - (state.days ?? 0),
    },
    invariants: {
      "A loan is overdue exactly when it is past its due date": (state) => {
        if (state.status === "ON_LOAN") return state.daysUntilDue !== undefined && state.daysUntilDue >= 0;
        if (state.status === "OVERDUE") return state.daysUntilDue !== undefined && state.daysUntilDue < 0;
        return true;
      },
    },
  },
});
