// Code generated by aac. DO NOT EDIT.
// ir-version: 1
// spec-hash:  sha256:3d5585f8cd2efd2b2cf2f259e905a5190ced43a364fb6a598cbef34cb104d815

export type StateName = "DRAFT" | "PENDING" | "PAID" | "SHIPPED" | "CANCELLED";

/** One action to execute: its name and the input that goes with it. */
export type Action =
  | { name: "Cancel"; input: {} }
  | { name: "Checkout"; input: {} }
  | { name: "PlaceOrder"; input: { customerRank: "Gold" | "Silver" | "Bronze"; listPrice: number } }
  | { name: "Ship"; input: {} };

/**
 * Stand-ins for everything the system depends on. The test harness owns them; connect them to
 * whatever seams your production code has.
 */
export type Ports = {
  /**
   * Values the system asks its environment for (a clock, configuration, the response of an external service).
   * Answers can differ between actions: ask when needed, do not cache.
   */
  queries: {
    isMonthEnd(): boolean;
    paymentModuleActive(): boolean;
    paymentResult(): "succeeded" | "failed";
  };
  /** Side effects the system performs on its environment. Calls are recorded in order and compared with the spec. */
  commands: {
    IssueCoupon(payload: { type: "Premium" | "Standard" }): void;
    NotifyPaymentFailure(payload: {}): void;
    Refund(payload: {}): void;
    SendOrderConfirmation(payload: {}): void;
    SendReceipt(payload: { amount: number; discountPercent: number }): void;
    SendShippingNotice(payload: { priority: boolean }): void;
  };
};

/** The test harness drives the production system only through this interface. */
export interface TargetSystemAdapter {
  /** Called before each trial. Build a fresh system in the initial state, connected to `ports`. */
  setupIsolation(ports: Ports): Promise<void>;
  /** Called after each trial, pass or fail. Discard everything the trial created. */
  teardownIsolation(): Promise<void>;
  /** Execute one action. A trial executes several actions in sequence on the same system. */
  executeAction(action: Action): Promise<void>;
  /** The current state of the system. */
  getCurrentState(): Promise<StateName>;
}
