// Code generated by aac. DO NOT EDIT.
// ir-version: 1
// spec-hash:  sha256:b2cdeaa31fc3f3ef406ea8bf7b04913aaad2ea5fa1ff791ee5fe7e277e608d06

export type StateName = "PENDING" | "PAID";
export type StateData = { isMonthEnd: boolean; paymentModuleActive: boolean; rank: "Gold" | "Silver" | "Bronze" };
export type Command =
  | { action: "IssueCoupon"; payload: { type: "Premium" | "Standard" } }
  | { action: "SendReceipt"; payload: { discount: number } };
export type ActionName = "Checkout";
export type Outcome = "PaymentSuccess";

// PBT はこのインターフェースだけを通して本番システムを操作する
export interface TargetSystemAdapter {
  /** 【分離契約】1回の試行の開始前に呼ばれる。本番システムをまっさらな状態にする。 */
  setupIsolation(): Promise<void>;
  /** 【分離契約】試行の終了後（成功・失敗問わず）に呼ばれる。副作用を完全に破棄する。 */
  teardownIsolation(): Promise<void>;
  /** 検証の出発点となる状態を本番システムに用意する。data は加工せずそのまま本番コードへ渡す。 */
  givenState(state: StateName, data: StateData): Promise<void>;
  /** アクションを実行する。outcome は IR の transitions のキー（アクションの結果の種類）。 */
  executeAction(action: ActionName, outcome: Outcome): Promise<void>;
  /** 現在の状態名を返す。 */
  getCurrentState(): Promise<StateName>;
  /** setupIsolation 以降に発行された Command を発行順に返す。 */
  getFiredCommands(): Promise<Command[]>;
}
