// Code generated by aac. DO NOT EDIT.
// ir-version: 3
// spec-hash:  sha256:1c17b9863d61c7c2981aae8876410d8ec2aefb48822c91d29a53567f7611e8ee

import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./order.adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../../../specs/", import.meta.url)), component: "order", adapter });
