// Code generated by aac. DO NOT EDIT.
// ir-version: 1
// spec-hash:  sha256:dc5dbaf114c72eee55b67501aef4a88a6625a6afcd2c5c525d523437cfb71ad0

import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../../../specs/", import.meta.url)), adapter });
