// Code generated by aac. DO NOT EDIT.
// ir-version: 1
// spec-hash:  sha256:96c1de9d7742e924caf0692af5a75d022ef64ec4ad12c26787efc21ffa30e5f2

import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../../../specs/", import.meta.url)), adapter });
