// Code generated by aac. DO NOT EDIT.
// ir-version: 1
// spec-hash:  sha256:b2cdeaa31fc3f3ef406ea8bf7b04913aaad2ea5fa1ff791ee5fe7e277e608d06

import { fileURLToPath } from "node:url";
import { runPbt } from "@aac/cli/runtime";
import { adapter } from "./adapter.ts";

await runPbt({ specs: fileURLToPath(new URL("../../../specs/", import.meta.url)), adapter });
